LU-15417 build: find the new path for MOFED 5.5
The path of the mofed header files has change to
/usr/src/ofa_kernel/x86_64/<kernel>,
so we cannot assume it's /usr/src/ofa_kernel/default.

Besides updating lbuild, we also need to update
lustre-lnet.m4 and lustre.spec.in.

Test-Parameters: trivial

Change-Id: Iab42ce9e458f78b0dc0233ac6fd23a1760be5324
Fixes: 94a3f1bfa70 ("LU-15417 build: build MOFED 5.5")
Signed-off-by: Jian Yu <yujian@whamcloud.com>
Reviewed-on: https://review.whamcloud.com/46383
Tested-by: jenkins <devops@whamcloud.com>
Tested-by: Maloo <maloo@whamcloud.com>
Reviewed-by: Andreas Dilger <adilger@whamcloud.com>
Reviewed-by: Minh Diep <mdiep@whamcloud.com>
Reviewed-by: Oleg Drokin <green@whamcloud.com>

diff --git a/lustre.spec.in b/lustre.spec.in
--- a/lustre.spec.in
+++ b/lustre.spec.in
@@ -472,6 +472,18 @@ fi
 %{?_openmpi_load}
 %{?_mpich_load}
 
+%if %{with mofed}
+	o2ib_path=$(find /usr/src/ofa_kernel/ -type d -name ofed_scripts | xargs dirname)
+	if [ -z "$o2ib_path" ]; then
+		echo "ERROR: could not find OFED devel headers"
+		exit 1
+	fi
+	if [ $(echo $o2ib_path | wc -w) -ge 2 ]; then
+		echo "ERROR: multiple OFED versions installed"
+		exit 1
+	fi
+%endif
+
 %eval_configure $CONFIGURE_ARGS \
 	%{?with_lustre_tests:--enable-tests}%{!?with_lustre_tests:--disable-tests} \
 	%{?with_lustre_utils:--enable-utils}%{!?with_lustre_utils:--disable-utils} \
@@ -488,7 +500,7 @@ fi
 	%{!?with_manpages:--disable-manpages} \
 	%{!?with_systemd:--with-systemdsystemunitdir=no} \
 	%{?with_systemd:--with-systemdsystemunitdir=%{_unitdir}} \
-	%{?with_mofed:--with-o2ib=/usr/src/ofa_kernel/default} \
+	%{?with_mofed:--with-o2ib=$o2ib_path} \
 	--with-linux=%{kdir} \
 	--with-linux-obj=%{kobjdir} \
 	--with-kmp-moddir=%{kmoddir}/%{name}
