LU-8383 build: Spec file cleanup after LU-5614
Add dependency from kmod-%{lustre_name}-tests
Fix BuildRequires: %kernel_module_package_buildreqs

Test-Parameters: trivial

Change-Id: I92325687812f10fb308971391e67bb80c08ae5db
Signed-off-by: Dmitry Eremin <dmitry.eremin@intel.com>
Reviewed-by: Christopher J. Morrone <morrone2@llnl.gov>
Reviewed-by: Bob Glossman <bob.glossman@intel.com>
Reviewed-by: Oleg Drokin <oleg.drokin@intel.com>
Reviewed-on: http://review.whamcloud.com/22125
Tested-by: Jenkins
Tested-by: Maloo <hpdd-maloo@intel.com>
Tested-by: Oleg Drokin <oleg.drokin@intel.com>

diff --git a/contrib/lbuild/lbuild-sles b/contrib/lbuild/lbuild-sles
--- a/contrib/lbuild/lbuild-sles
+++ b/contrib/lbuild/lbuild-sles
@@ -58,6 +58,13 @@ prepare_and_build_srpm() {
         fatal 1 "Failed to build kernel source RPM"
     fi
 
+    # for SLES, we also need to build the kernel-syms rpm
+    if ! rpmbuild $rpmbuildopt $targets \
+                   --define "_topdir $TOPDIR" \
+                   $TOPDIR/SOURCES/kernel-syms.spec 2>&1; then
+        fatal 1 "Failed to build kernel syms RPM"
+    fi
+
 }
 
 devel_kernel_name() {
