LU-3962 utils: improve names of iokit tools
Some of the names of scripts in the lustre-iokit package are very
generic and may easily cause confusion for users, or conflict with
other installations.  Rename them to more unique names and update
the files that reference them.

Fix whitespace in renamed files.

Signed-off-by: Andreas Dilger <andreas.dilger@intel.com>
Change-Id: I733428467e5604bf9db916491e041253323ebbe5
Reviewed-on: http://review.whamcloud.com/10183
Tested-by: Jenkins
Tested-by: Maloo <hpdd-maloo@intel.com>
Reviewed-by: Dmitry Eremin <dmitry.eremin@intel.com>
Reviewed-by: Minh Diep <minh.diep@intel.com>
Reviewed-by: Oleg Drokin <oleg.drokin@intel.com>

diff --git a/lustre-iokit/obdfilter-survey/iokit-libecho b/lustre-iokit/obdfilter-survey/iokit-libecho
--- a/lustre-iokit/obdfilter-survey/iokit-libecho
+++ b/lustre-iokit/obdfilter-survey/iokit-libecho
@@ -1,4 +1,7 @@
 #!/bin/bash
+# -*- mode: Bash; tab-width: 4; indent-tabs-mode: t; -*-
+# vim:shiftwidth=4:softtabstop=4:tabstop=4:
+#
 # GPL HEADER START
 #
 # DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
@@ -63,17 +66,17 @@ dsh () {
 
     case $DSH in
 	ssh)
-	    if [ -n "$user" ]; then
-		user="$user@"
-	    fi
-	    $DSH $user$node "$command"
-	    ;;
+		if [ -n "$user" ]; then
+			user="$user@"
+		fi
+		$DSH $user$node "$command"
+		;;
 	rsh)
-	    if [ -n "$user" ]; then
-		user="-l $user"
-	    fi
-	    $DSH $user $node "$command"
-	    ;;
+		if [ -n "$user" ]; then
+			user="-l $user"
+		fi
+		$DSH $user $node "$command"
+		;;
     esac
 }
 
@@ -85,16 +88,16 @@ remote_shell () {
     shift
     cmds="$@"
     if [ "$host" = "localhost" -o "$host" = `uname -n` ]; then
-	eval "$cmds"
+		eval "$cmds"
     else
-	# split $host into $host and $user
-	local user=""
-	if [[ $host == *@* ]]; then
-	    user=${host%@*}
-	    host=${host#*@}
+		# split $host into $host and $user
+		local user=""
+		if [[ $host == *@* ]]; then
+			user=${host%@*}
+			host=${host#*@}
+		fi
+		dsh $host "$user" "$cmds"
 	fi
-	dsh $host "$user" "$cmds"
-    fi
 }
 
 # checks whether obdecho module is loded on given host.
@@ -108,6 +111,7 @@ obdecho_loaded() {
 load_obdecho () {
     local index=$1
     local host=${unique_hosts[$index]}
+
     do_unload_echo[$index]=0
     if obdecho_loaded $host; then
         return 0
@@ -129,9 +133,9 @@ load_obdecho () {
 }
 
 load_obdechos () {
-    for ((i = 0; i < ${#unique_hosts[@]}; i++)); do
-                load_obdecho $i || cleanup 1
-    done
+	for ((i = 0; i < ${#unique_hosts[@]}; i++)); do
+		load_obdecho $i || cleanup 1
+	done
 }
 
 # unload obdecho module from host kernel.
@@ -153,8 +157,9 @@ get_devno () {
     local host=$1
     local type=$2
     local name=$3
-    remote_shell $host $lctl device_list | \
-	awk "{if (\$2 == \"UP\" && \$3 == \"$type\" && \$4 == \"$name\") {\
+
+    remote_shell $host $lctl device_list |
+		awk "{if (\$2 == \"UP\" && \$3 == \"$type\" && \$4 == \"$name\") {\
 	          print \$1; exit}}"
 }
 
@@ -167,7 +172,7 @@ get_devnos () {
         dev=$(get_devno $host obdfilter $ost)
         dev_list[$i]=$dev
         if [ -z "$dev" ]; then
-            echo Cant find device for $ost on $host
+			echo "Cannot find device for $ost on $host"
             return 1
         fi
     done
@@ -176,81 +181,83 @@ get_devnos () {
 
 # do cleanup for netdisk case.
 cleanup_netdisk () {
-    for osc in $@; do
-	$lctl <<-EOF
-		cfg_device $osc
-		cleanup
-		detach
-	EOF
-    done
+	for osc in $@; do
+		$lctl <<-EOF
+			cfg_device $osc
+			cleanup
+			detach
+		EOF
+	done
 }
 
 # do cleanup for network case.
 cleanup_network () {
-    local clean_srv_OSS=$1
+	local clean_srv_OSS=$1
+
 	$lctl <<-EOF
 		cfg_device echotmp
 		cleanup
 		detach
 	EOF
-    remote_shell "root@$server_nid" \
+	remote_shell "root@$server_nid" \
 	"$lctl <<-EOF
 		cfg_device echo_srv
 		cleanup
 		detach
 	EOF"
-    if [ $clean_srv_OSS ]; then
-        remote_shell "root@$server_nid" \
-	"$lctl <<-EOF
-		cfg_device OSS
-		cleanup
-		detach
-	EOF"
-    fi
+	if [ $clean_srv_OSS ]; then
+		remote_shell "root@$server_nid" \
+		"$lctl <<-EOF
+			cfg_device OSS
+			cleanup
+			detach
+		EOF"
+	fi
 }
 
 # do cleanup and exit.
 cleanup () {
-    local exit_status=$1
-    local host
-    case=${case:-"disk"}
-    shift
-    for ((i = 0; i < $ndevs; i++)); do
-        host=${host_names[$i]}
-        if [[ -n "${do_teardown_ec[$i]}" ]]; then
-            teardown_ec_devno $host ${client_names[$i]}
-        fi
-    done
-    pidcount=0
-    for ((i = 0; i < ${#unique_hosts[@]}; i++)); do
-        host=${unique_hosts[$i]}
-        remote_shell $host "killall -q vmstat >/dev/null 2>&1" &
-        pid=$!
-        kill -term ${vmstatpids[$pidcount]} 2>/dev/null
-        kill -kill ${vmstatpids[$pidcount]} 2>/dev/null
-        wait $pid
-        pidcount=$((pidcount+1))
-        if ((${do_unload_echo[$i]})); then
-            unload_obdecho $i
-        fi
-    done
-    if [ $case == "network" ]; then
-        cleanup_network $1
-    fi
-    if [ $case == "netdisk" ]; then
-        shift
-        cleanup_netdisk $@
-    fi
-    if [ $exit_status ]; then
-        if [ $exit_status -ne 0 ]; then
-            echo "program exited with error "
-        else
-            echo "done!"
-        fi
-    else
-        echo "Terminated"
-    fi
-    exit $exit_status
+	local exit_status=$1
+	local host
+
+	case=${case:-"disk"}
+	shift
+	for ((i = 0; i < $ndevs; i++)); do
+		host=${host_names[$i]}
+		if [[ -n "${do_teardown_ec[$i]}" ]]; then
+			teardown_ec_devno $host ${client_names[$i]}
+		fi
+	done
+	pidcount=0
+	for ((i = 0; i < ${#unique_hosts[@]}; i++)); do
+		host=${unique_hosts[$i]}
+		remote_shell $host "killall -q vmstat >/dev/null 2>&1" &
+		pid=$!
+		kill -term ${vmstatpids[$pidcount]} 2>/dev/null
+		kill -kill ${vmstatpids[$pidcount]} 2>/dev/null
+		wait $pid
+		pidcount=$((pidcount + 1))
+		if ((${do_unload_echo[$i]})); then
+			unload_obdecho $i
+		fi
+	done
+	if [ $case == "network" ]; then
+		cleanup_network $1
+	fi
+	if [ $case == "netdisk" ]; then
+		shift
+		cleanup_netdisk $@
+	fi
+	if [ $exit_status ]; then
+		if [ $exit_status -ne 0 ]; then
+		echo "program exited with error "
+		else
+		echo "done!"
+		fi
+	else
+		echo "Terminated"
+	fi
+	exit $exit_status
 }
 trap 'cleanup 0 $clean_srv_OSS $cleanup_oscs' SIGHUP SIGINT SIGTERM
 
@@ -262,54 +269,55 @@ trap 'cleanup 0 $clean_srv_OSS $cleanup_oscs' SIGHUP SIGINT SIGTERM
 #            2. client name, ex:- ns8:ECHO_ns8
 #            3. name of ost instances, ex:- lustre-OST0001
 get_ec_devno () {
-    exec 8>&1 1>&2
-    local host=$1
-    local client_name="$2"
-    local ost_name="$3"
-    local dev_type="${4:-obdfilter}"
-    local stack_type="${5:-}"
+	exec 8>&1 1>&2
+	local host=$1
+	local client_name="$2"
+	local ost_name="$3"
+	local dev_type="${4:-obdfilter}"
+	local stack_type="${5:-}"
 
-    if [ -z "$client_name" ]; then
-        if [ -z "$ost_name" ]; then
-            echo "client and ost name both null"
-            exit 1
-    fi
-        client_name=${ost_name}_ecc
-    fi
-    ec=`get_devno $host echo_client $client_name`
-    if [ -n "$ec" ]; then
-        echo $ec $client_name $client_name >&8
-        exit 0
-    fi
-    if [ -z "$ost_name" ]; then
-        echo "no echo client and ost_name not set, client:" \
-            "$client_name, host: $host"
-        exit 1
-    fi
-    ost=`get_devno $host $dev_type $ost_name`
-    if [ -z "$ost" ]; then
-        echo "OST $ost_name not setup"
-        exit 1
-    fi
-    client_name=${ost_name}_ecc
-    remote_shell $host \
-	"$lctl <<-EOF
-		attach echo_client $client_name ${client_name}_UUID
-		setup $ost_name $stack_type
-	EOF"
-    ec=`get_devno $host echo_client $client_name`
-    if [ -z "$ec" ]; then
-        echo "Can't setup echo-client"
-        exit 1
-    fi
-    echo $ec $client_name 1 >&8
-    exit 0
+	if [ -z "$client_name" ]; then
+		if [ -z "$ost_name" ]; then
+			echo "client and ost name both null"
+			exit 1
+		fi
+		client_name=${ost_name}_ecc
+	fi
+	ec=$(get_devno $host echo_client $client_name)
+	if [ -n "$ec" ]; then
+		echo $ec $client_name $client_name >&8
+		exit 0
+	fi
+	if [ -z "$ost_name" ]; then
+		echo "no echo client and ost_name not set, client:" \
+			"$client_name, host: $host"
+		exit 1
+	fi
+	ost=$(get_devno $host $dev_type $ost_name)
+	if [ -z "$ost" ]; then
+		echo "OST $ost_name not setup"
+		exit 1
+	fi
+	client_name=${ost_name}_ecc
+	remote_shell $host \
+		"$lctl <<-EOF
+			attach echo_client $client_name ${client_name}_UUID
+			setup $ost_name $stack_type
+		EOF"
+	ec=$(get_devno $host echo_client $client_name)
+	if [ -z "$ec" ]; then
+		echo "Can't setup echo-client"
+		exit 1
+	fi
+	echo $ec $client_name 1 >&8
+	exit 0
 }
 
 # Create echo-clients using osc_names and osc_uuid
 # It creates echoclients for all osc listed using #lctl device_list command
 ec_using_osc () {
-    local osc_name=$1
+	local osc_name=$1
+
 	$lctl <<-EOF
 		attach echo_client ${osc_name}_ecc ${osc_name}_ecc_UUID
 		cfg_device ${osc_name}_ecc
@@ -320,10 +328,11 @@ ec_using_osc () {
 
 # create echo client using server nid.
 ec_using_srv_nid () {
-    local server_nid=$1
-    local ocsname=$2
-    local oscuuid=$3
-    $lctl add_uuid echo_UUID $server_nid@$NETTYPE >/dev/null 2>&1
+	local server_nid=$1
+	local ocsname=$2
+	local oscuuid=$3
+
+	$lctl add_uuid echo_UUID $server_nid@$NETTYPE >/dev/null 2>&1
 	$lctl <<-EOF
 		attach osc $ocsname $oscuuid
 		cfg_device $ocsname
@@ -336,10 +345,11 @@ ec_using_srv_nid () {
 }
 
 setup_osc_for_remote_ost () {
-    local ost_nid=$1
-    local obdfilter_name=$2
-    local host_name=host_$3
-    $lctl add_uuid ${host_name}_UUID $ost_nid@$NETTYPE >/dev/null 2>&1
+	local ost_nid=$1
+	local obdfilter_name=$2
+	local host_name=host_$3
+
+	$lctl add_uuid ${host_name}_UUID $ost_nid@$NETTYPE >/dev/null 2>&1
 	$lctl <<-EOF
 		attach osc ${obdfilter_name}_osc ${obdfilter_name}_osc_UUID
 		cfg_device ${obdfilter_name}_osc
@@ -349,9 +359,10 @@ setup_osc_for_remote_ost () {
 
 # setup obdecho on server
 setup_srv_obd () {
-    local server_nid=$1
-    local test_ostfsnm=$2
-    remote_shell "root@$server_nid" \
+	local server_nid=$1
+	local test_ostfsnm=$2
+
+	remote_shell "root@$server_nid" \
 	"$lctl <<-EOF
 		attach obdecho $test_ostfsnm ${test_ostfsnm}_UUID
 		cfg_device $test_ostfsnm
@@ -361,8 +372,9 @@ setup_srv_obd () {
 
 # setup OSS on server
 setup_OSS () {
-    local server_nid=$1
-    remote_shell "root@$server_nid" \
+	local server_nid=$1
+
+	remote_shell "root@$server_nid" \
 	"$lctl <<-EOF
 		attach ost OSS OSS_UUID
 		cfg_device OSS
@@ -374,9 +386,10 @@ setup_OSS () {
 # parameter: 1. hostname
 #            2. client name, ex:- ns8:ECHO_ns8
 teardown_ec_devno () {
-    local host=$1
-    local client_name=$2
-    remote_shell $host \
+	local host=$1
+	local client_name=$2
+
+	remote_shell $host \
 	"$lctl <<-EOF
 		cfg $client_name
 		cleanup
@@ -385,75 +398,79 @@ teardown_ec_devno () {
 }
 
 unique () {
-    echo "$@" | xargs -n1 echo | sort -u
+	echo "$@" | xargs -n1 echo | sort -u
 }
 
 split_hostname () {
-    local name=$1
-    case $name in
-    *:*) host=`echo $name | sed 's/:.*$//'`
-         name=`echo $name | sed 's/[^:]*://'`
-         ;;
-    *)   host=localhost
-         ;;
-    esac
-    echo "$host $name"
+	local name=$1
+
+	case $name in
+	*:*) host=$(echo $name | sed 's/:.*$//')
+		name=$(echo $name | sed 's/[^:]*://')
+		;;
+	*)   host=localhost
+		;;
+	esac
+	echo "$host $name"
 }
 
 check_cleanup () {
-    type_obj="$1"
-    osc_names_str=$($lctl dl | grep $type_obj)
-    count=0;
-    for name in $osc_names_str; do
-        count=$((count+1))
-    done
+	local type_obj="$1"
+	local osc_names_str=$($lctl dl | grep $type_obj)
+	local count=0;
 
-    if [ $count != 0 ]; then
-        echo "$type_obj could not be cleanup";
-        exit 0;
-    fi
+	for name in $osc_names_str; do
+		count=$((count + 1))
+	done
+
+	if [ $count != 0 ]; then
+		echo "$type_obj could not be cleanup";
+		exit 0;
+	fi
 
 }
 
 check_setup () {
-    type_obj="$1"
-    osc_names_str=$($lctl dl | grep $type_obj)
-    count=0;
-    for name in $osc_names_str; do
-        count=$((count+1))
-    done
+	local type_obj="$1"
+	local osc_names_str=$($lctl dl | grep $type_obj)
+	local count=0;
 
-    if [ $count == 0 ]; then
-        echo "$type_obj could not be setup";
-        exit 0;
-    fi
+	for name in $osc_names_str; do
+		count=$((count + 1))
+			done
+
+	if [ $count == 0 ]; then
+		echo "$type_obj could not be setup";
+		exit 0;
+	fi
 
 }
 
 # added from bugzill req.
 get_targets () {
-    if [ -z "$ost_names" ]; then
-        targets=$($lctl device_list | awk "{if (\$2 == \"UP\" && \
-            \$3 == \"obdfilter\") {print \$4} }")
-    fi
-    if [ -z "$targets" ]; then
-        echo "Can't find any OSTs to test.  Please set targets=..."
-        exit 1
-    fi
-    count=0
-    for name in $targets; do
-        ost_names[$count]=$name
-        str=(`split_hostname $name`)
-        host_names[$count]=${str[0]}
-        count=$((count+1))
-    done
+	if [ -z "$ost_names" ]; then
+		targets=$($lctl device_list | awk "{if (\$2 == \"UP\" && \
+			  \$3 == \"obdfilter\") {print \$4} }")
+	fi
+	if [ -z "$targets" ]; then
+		echo "Can't find any OSTs to test.  Please set targets=..."
+		exit 1
+	fi
+
+	local count=0
+	for name in $targets; do
+		ost_names[$count]=$name
+		str=($(split_hostname $name))
+		host_names[$count]=${str[0]}
+		count=$((count + 1))
+	done
 }
 
 get_hosts () {
-    # split out hostnames from ost names
-    for ((i = 0; i < count; i++)); do
-        str=(`split_hostname ${targets[$i]}`)
-        host_list[$i]=${str[0]}
-        ost_names[$i]=${str[1]}
-    done
+	# split out hostnames from ost names
+	for ((i = 0; i < count; i++)); do
+		local str=($(split_hostname ${targets[$i]}))
+		host_list[$i]=${str[0]}
+		ost_names[$i]=${str[1]}
+	done
 }
diff --git a/lustre-iokit/stats-collect/iokit-gather-stats b/lustre-iokit/stats-collect/iokit-gather-stats
--- a/lustre-iokit/stats-collect/iokit-gather-stats
+++ b/lustre-iokit/stats-collect/iokit-gather-stats
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-# gather_stats_everywhere:
+# iokit-gather-stats:
 # script on a selection of nodes and collect all the results into a single
 # tar ball
 #
@@ -12,60 +12,56 @@ error() {
 }
 
 warning() {
-        echo "WARNING: $@"
+	echo "WARNING: $@"
 }
 
 info () {
-        if [ ${PRINT_INFO_MSGS} -gt 0 ]
-        then
-                echo "INFO: $@"
-        fi
+	if [ ${PRINT_INFO_MSGS} -gt 0 ]; then
+		echo "INFO: $@"
+	fi
 }
 
 debug () {
-        if [ ${PRINT_DEBUG_MSGS} -gt 0 ]
-        then
-                echo "DEBUG: $@"
-        fi
+	if [ ${PRINT_DEBUG_MSGS} -gt 0 ]; then
+		echo "DEBUG: $@"
+	fi
 }
 
 usage() {
-	printf $"Usage: gather_stats_everywhere [-help] config_file [start|stop|cleanup] <log_name>\n"
-	if [ x$1 = x-h ]
-	then
+	printf $"Usage: iokit-gather-stats [-help] config_file [start|stop|cleanup] <log_name>\n"
+	if [ x$1 = x-h ]; then
 		 printf $"
-The distribution script will run on a single node.  It is parameterised 
-with a set of target node names.  It may assume ssh/scp to these node 
+The distribution script will run on a single node.  It is parameterised
+with a set of target node names.  It may assume ssh/scp to these node
 names works without requiring a password.  It will run in 2 modes...
 
-gather_stats_everywhere config_file start
+iokit-gather-stats config_file start
 
 ...will copy the script to /tmp everywhere described in
 config_file running on all the target hosts.  And...
 
-gather_stats_everywhere config_file stop log_name
+iokit-gather-stats config_file stop log_name
 
-...will stop script running on all the hosts it started on and collect 
+...will stop script running on all the hosts it started on and collect
 all the individual stats files into a single compressed tarball if the log_name is
 provided.
 
 The config file is just a list of shell variable assignments that can be
-customised. 
+customised.
 
 Serveral variables must be set in the config file
 
 Targets: the nodes where run the script.
 "
-		 exit 0
+		exit 0
 	else
-	 	 exit 1
+		exit 1
 	fi
 }
 
 options=`getopt -o h --long help:: -- "$@"`
 
-if [ $? -ne 0 ]
-then 
+if [ $? -ne 0 ]; then
 	usage
 fi
 
@@ -78,14 +74,14 @@ do
 			usage -h ;;
 		--help)
 			usage -h ;;
-	        --)
+		--)
 			shift
 			break ;;
 	esac
 done
 
 if [ $# != 2 -a $# != 3 ] ; then
-       	usage
+	usage
 fi
 
 CONFIG=$1
@@ -103,39 +99,41 @@ fi
 . $CONFIG
 
 if [ -z "$SCRIPT" ]; then
-       	error "SCRIPT in ${CONFIG} is empty"
-       	exit 1
-fi	
-
-if [ -z "$TARGETS" ]; then
-       	error "TARGETS in ${CONFIG} is empty"
-       	exit 1
+	error "SCRIPT in ${CONFIG} is empty"
+	exit 1
 fi
 
-#check nodes accessiable 
-Check_nodes_available() {
-        local NODES_NOT_AVAILABLE=""
+if [ -z "$TARGETS" ]; then
+	error "TARGETS in ${CONFIG} is empty"
+	exit 1
+fi
 
-        debug "Entering Check_nodes_available()"
-    
+#check nodes accessiable
+Check_nodes_available() {
+	local NODES_NOT_AVAILABLE=""
+
+	debug "Entering Check_nodes_available()"
+
 	for TARGET in $TARGETS; do
-                if ! ping -c 1 -w 3 $TARGET > /dev/null; then 
-                        NODES_NOT_AVAILABLE=$NODES_NOT_AVAILABLE$TARGET
-                fi
-        done
-    
+		if ! ping -c 1 -w 3 $TARGET > /dev/null; then
+			NODES_NOT_AVAILABLE=$NODES_NOT_AVAILABLE$TARGET
+		fi
+	done
+
 	if [ -z "$NODES_NOT_AVAILABLE" ]; then
-	        debug "Check_nodes_available() returning 0 (success - all nodes available)"
+		debug "Check_nodes_available() returning 0 "
+			"(success - all nodes available)"
 		return 0
 	fi
 
-        error "Check_nodes_available: these nodes are not available (did not respond to pings): ${NODES_NOT_AVAILABLE}"
-        debug "Check_nodes_available() returning with errors"
-        
+	error "Check_nodes_available: these nodes are not available "
+		"(did not respond to pings): ${NODES_NOT_AVAILABLE}"
+	debug "Check_nodes_available() returning with errors"
+
 	return 1
 }
 
-if ! Check_nodes_available;  then 
+if ! Check_nodes_available; then
 	error "not all the nodes are available"
 	exit 1
 fi
@@ -146,84 +144,84 @@ fi
 Nodes_are_not_clean() {
 	local DIRTY_NODES=""
 
-        debug "Entering Nodes_are_not_clean()"
-    
+	debug "Entering Nodes_are_not_clean()"
+
 	# check whether there are running threads on the targets
 	for TARGET in $TARGETS; do
 		ps_str=`$DSH $TARGET "ps aux | grep -v grep | grep ${SCRIPT}-${TARGET}"`
 		if [ -n "$ps_str" ]; then
-		       	DIRTY_NODES="${DIRTY_NODES} ${TARGET}"
+			DIRTY_NODES="${DIRTY_NODES} ${TARGET}"
 		fi
 	done
 
 	if [ -n "$DIRTY_NODES" ]; then
-	        debug "Nodes_are_not_clean() returning 1"
+		debug "Nodes_are_not_clean() returning 1"
 		return 1
 	fi
 
-        debug "Nodes_are_not_clean() returning 0"
-	return 0 
+	debug "Nodes_are_not_clean() returning 0"
+	return 0
 }
 
 Clean_nodes() {
 
-        debug "Entering Clean_nodes()"
-    
-        #
-        # if debugging is enabled, show lists of lstats processes
-        # still running on the target nodes before the clean operation
-        #
-        if [ ${PRINT_DEBUG_MSGS} -gt 0 ]
-        then
-                for TARGET in $TARGETS; do
-                        debug "List of processes which need to be cleaned up on ${TARGET}:"
-                        $DSH $TARGET "ps aux | grep -v grep | grep ${SCRIPT}-${TARGET}"
-                        debug "List of pids which need to be cleaned up on ${TARGET}:"
-                        $DSH $TARGET "ps aux | grep ${SCRIPT}-${TARGET} | grep -v grep | ${AWK} '{ print \$2 }'"
-                done
-        fi
-    
-        #
-        # do the actual cleanup
+	debug "Entering Clean_nodes()"
+
+	#
+	# if debugging is enabled, show lists of lstats processes
+	# still running on the target nodes before the clean operation
+	#
+	if [ ${PRINT_DEBUG_MSGS} -gt 0 ]; then
+		for TARGET in $TARGETS; do
+			debug "List of processes which need to be cleaned up on ${TARGET}:"
+			$DSH $TARGET "ps aux | grep -v grep | grep ${SCRIPT}-${TARGET}"
+			debug "List of pids which need to be cleaned up on ${TARGET}:"
+			$DSH $TARGET "ps aux | grep ${SCRIPT}-${TARGET} | grep -v grep | ${AWK} '{ print \$2 }'"
+		done
+	fi
+
+	#
+	# do the actual cleanup
 	# kill any old lstats processes still running on the target nodes
 	#
 	for TARGET in $TARGETS; do
-	    
-                ps_str=`$DSH $TARGET "ps aux | grep -v grep | grep ${SCRIPT}-${TARGET}"`
-                if [ -n "$ps_str" ]; then
-                        debug "cleaning node ${TARGET}"
-                        $DSH $TARGET "ps aux | grep ${SCRIPT}-${TARGET} | grep -v grep | ${AWK} '{ print \$2 }' | ${XARGS} kill"
-                fi
-        done
+		ps_str=$($DSH $TARGET "ps aux | grep -v grep | grep ${SCRIPT}-${TARGET}")
+		if [ -n "$ps_str" ]; then
+			debug "cleaning node ${TARGET}"
+			$DSH $TARGET "ps aux | grep ${SCRIPT}-${TARGET} |
+				      grep -v grep | ${AWK} '{ print \$2 }' |
+				      ${XARGS} kill"
+		fi
+	done
 
-        debug "Leaving Clean_nodes()"
-	return 0 
+	debug "Leaving Clean_nodes()"
+	return 0
 }
 
 copy_target_script() {
 	local target=$1
 
-        debug "Entering copy_target_script()"
-    
+	debug "Entering copy_target_script()"
+
 	#copy alex's run scripts to the target
 	copy_cmd="$DCP $SCRIPT ${USER}${target}:$TMP/${SCRIPT}-${target}"
-	${copy_cmd} 1>/dev/null 2>&1 
-        if [ ${PIPESTATUS[0]} != 0 ]; then
+	${copy_cmd} 1>/dev/null 2>&1
+	if [ ${PIPESTATUS[0]} != 0 ]; then
 		echo "copy command failed: ${copy_cmd}" 2>&1
 		debug "Leaving copy_target_script() (error return)"
 		return 1
 	fi
-	
-        echo "$SCRIPT copied to ${USER}${target} (into $TMP)"
-        debug "Leaving copy_target_script() (normal return)"
+
+	echo "$SCRIPT copied to ${USER}${target} (into $TMP)"
+	debug "Leaving copy_target_script() (normal return)"
 	return 0
 }
 
 start_target_script() {
 	local target=$1
 
-        debug "Entering start_target_script()"
-    
+	debug "Entering start_target_script()"
+
 	if ! copy_target_script $target; then
 		echo "copy_target_script $target failed." 2>&1
 		debug "Leaving start_target_script() (error return)"
@@ -232,13 +230,13 @@ start_target_script() {
 
 	#run the script on the target
 	$DSH ${USER}${target} "VMSTAT_INTERVAL=${VMSTAT_INTERVAL} \
-		      SDIO_INTERVAL=${SDIO_INTERVAL} \
-		      SERVICE_INTERVAL=${SERVICE_INTERVAL} \
-		      BRW_INTERVAL=${BRW_INTERVAL} 	   \
-		      JBD_INTERVAL=${JBD_INTERVAL}	   \
-		      IO_INTERVAL=${IO_INTERVAL}	   \
-		      MBALLOC_INTERVAL=${MBALLOC_INTERVAL} \
-		      sh ${TMP}/${SCRIPT}-${target} start  \
+		      SDIO_INTERVAL=${SDIO_INTERVAL}		  \
+		      SERVICE_INTERVAL=${SERVICE_INTERVAL}	  \
+		      BRW_INTERVAL=${BRW_INTERVAL}		  \
+		      JBD_INTERVAL=${JBD_INTERVAL}		  \
+		      IO_INTERVAL=${IO_INTERVAL}		  \
+		      MBALLOC_INTERVAL=${MBALLOC_INTERVAL}	  \
+		      sh ${TMP}/${SCRIPT}-${target} start	  \
 		      1> /dev/null 2>/dev/null </dev/null"
 
 	if [ ${PIPESTATUS[0]} != 0 ]; then
@@ -246,7 +244,7 @@ start_target_script() {
 		debug "Leaving start_target_script() (error return)"
 		return 1
 	fi
-		
+
 	echo "Start the ${SCRIPT} on ${target} success"
 	debug "Leaving start_target_script() (normal return)"
 	return 0
@@ -255,24 +253,24 @@ start_target_script() {
 stop_target_script() {
 	local target=$1
 
-        debug "Entering stop_target_script()"
-    
+	debug "Entering stop_target_script()"
+
 	#stop the target script first
 	$DSH ${USER}${target} "sh ${TMP}/${SCRIPT}-${target} stop" 1>/dev/null 2>&1
 	if [ ${PIPESTATUS[0]} != 0 ]; then
 		echo  "stop the collecting stats script on ${target} failed"
 		debug "Leaving stop_target_script() (error return)"
-		return 1 
-	else	
+		return 1
+	else
 		echo  "stop the collecting stats script on ${target} success"
 	fi
 
 	#remove those tmp file
 	$DSH ${USER}${target} "rm -rf $TMP/${SCRIPT}-${target}" 1>/dev/null 2>&1
 	echo "cleanup ${target} tmp file after stop "
-	
+
 	debug "Leaving stop_target_script() (normal return)"
-        return 0
+	return 0
 }
 
 #
@@ -285,8 +283,7 @@ stop_target_script() {
 # different from the clock on this node)
 #
 generate_timestamp() {
-	if [ "X${GLOBAL_TIMESTAMP}" = "X" ]
-	then
+	if [ "X${GLOBAL_TIMESTAMP}" = "X" ]; then
 		export GLOBAL_TIMESTAMP=`date +%F-%H.%M.%S`
 		debug "Global Timestamp Created: ${GLOBAL_TIMESTAMP}"
 	fi
@@ -314,31 +311,31 @@ fetch_log() {
 	local -a pids_array
 	local -a clients_array
 
-        debug "Entering fetch_log()"
-    
+	debug "Entering fetch_log()"
+
 	if ! mkdir -p $TMP/$log_name ; then
 		error "can not mkdir $log_name"
 		exit 1
 	fi
 
-    	#retrive the log_tarball from remote nodes background 
-        local n=0
+	#retrive the log_tarball from remote nodes background
+	local n=0
 	for TARGET in $TARGETS; do
-		(fetch_target_log ${TARGET}) & 
+		(fetch_target_log ${TARGET}) &
 		pids_array[$n]=$!
 		clients_array[$n]=$TARGET
-		
+
 		debug "fetch_log: spawned fetch_target_log process for ${TARGET} pid ${pids_array[$n]}"
-                let n=$n+1
+		let n=$n+1
 	done
-	
+
 	local num_pids=$n
 
 	#Waiting log fetch finished
 	for ((n=0; $n < $num_pids; n++)); do
-	        debug "fetch_log(): waiting for pid ${pids_array[$n]}"
+		debug "fetch_log(): waiting for pid ${pids_array[$n]}"
 		wait ${pids_array[$n]}
-		
+
 		#
 		# TODO: add check of exit status from wait()
 		#
@@ -347,14 +344,14 @@ fetch_log() {
 	#compress the log tarball
 	cmd="$TAR ${stat_tar_name} $TMP/${log_name}"
 	echo "Creating compressed tar file ${stat_tar_name} from log files in  $TMP/${log_name}"
-	${cmd} 1>/dev/null 2>&1 
-       	if [ ${PIPESTATUS[0]} == 0 ]; then
+	${cmd} 1>/dev/null 2>&1
+	if [ ${PIPESTATUS[0]} == 0 ]; then
 		echo "removing temporary directory $TMP/${log_name}"
 		rm -rf $TMP/${log_name}
 	else
 		echo "Compressed logfiles are in $TMP/${stat_tar_name}"
 	fi
-	
+
 	debug "Leaving fetch_log()"
 }
 
@@ -362,68 +359,66 @@ stop_targets_script() {
 	local -a pids_array
 	local -a clients_array
 	local n=0
-	
+
 	debug "Entering stop_targets_script()"
-	
+
 	for TARGET in $TARGETS; do
 		(stop_target_script ${TARGET}) &
 		pids_array[$n]=$!
 		clients_array[$n]=$TARGET
-	        let n=$n+1
+		let n=$n+1
 	done
 	local num_pids=$n
-	
+
 	#Waiting log fetch finished
 	for ((n=0; $n < $num_pids; n++)); do
 		if ! wait ${pids_array[$n]}; then
 			echo "${clients_array[$n]}: can not stop stats collect"
 		fi
 	done
-	
+
 	debug "Leaving stop_targets_script()"
-	
 }
 
 gather_start() {
 	local -a pids_array
 	local -a clients_array
 	local n=0
-	
-	debug "Entering gather_start()"
-	
-	#check whether the collect scripts already start in some targets 
 
-        Nodes_are_not_clean
-        ret=$?
-    
-	if [ $ret -gt 0 ]
-	then
-	    warning "$SCRIPT already running in some targets, attempting cleanup..."
-	    
-	    Clean_nodes
-	    
-	    Nodes_are_not_clean
-	    ret=$?
-	    
-	    if [ $ret -gt 0 ]
-	    then
-	        error "$SCRIPT automatic cleanup attempt failed."
-	        error "$SCRIPT Please make sure lstats is no longer running on target nodes and try again."
-	        debug "Error return from gather_start()"
-	        return 1
-	    fi
+	debug "Entering gather_start()"
+
+	#check whether the collect scripts already start in some targets
+
+	Nodes_are_not_clean
+	ret=$?
+
+	if [ $ret -gt 0 ]; then
+		warning "$SCRIPT already running on some targets, try cleanup"
+
+		Clean_nodes
+
+		Nodes_are_not_clean
+		ret=$?
+
+		if [ $ret -gt 0 ]; then
+			error "$SCRIPT automatic cleanup attempt failed."
+			error "$SCRIPT Please make sure lstats is not running "\
+				"on target nodes and try again."
+			debug "Error return from gather_start()"
+			return 1
+		fi
 	fi
-	
+
 	for TARGET in $TARGETS; do
 		(start_target_script ${TARGET}) &
 		pids_array[$n]=$!
 		clients_array[$n]=$TARGET
-	        let n=$n+1
+		let n=$n+1
 	done
-	
+
 	local num_pids=$n
 
-	local RC=0	
+	local RC=0
 	#Waiting log fetch finished
 	for ((n=0; $n < $num_pids; n++)); do
 		if ! wait ${pids_array[$n]}; then
@@ -435,21 +430,21 @@ gather_start() {
 	if [ $RC != 0 ]; then
 		stop_targets_script
 	fi
-	
+
 	debug "Leaving gather_start()"
 }
 
 gather_stop() {
 	log=$1
 
-        debug "Entering gather_stop()"
-    
+	debug "Entering gather_stop()"
+
 	if [ -n "$log" ]; then
 		fetch_log $log
 	fi
-	
+
 	stop_targets_script
-	
+
 	debug "Leaving gather_stop()"
 }
 
@@ -457,10 +452,11 @@ get_end_line_num()
 {
 	local log_name=$1
 
-	ln=`grep -n snapshot_time ${log_name}  | awk -F":" '{ln=$1;} END{print ln;}'`
-	total_ln=`wc ${log_name} | awk '{print $1}'`			
+	local ln=$(grep -n snapshot_time ${log_name} |
+		   awk -F":" '{ln=$1;} END{print ln;}')
+	local total_ln=$(wc ${log_name} | awk '{print $1}')
 
-	local endlen=$((${total_ln} - ${ln}))
+	local endlen=$((total_ln - $ln))
 	echo $endlen
 }
 
@@ -491,11 +487,11 @@ get_csv()
 			tail -n $end_len ${statf} | awk '{print $1 "," $2}' \
 				>> $logdir/analyse_${type_name}.csv
 		else
-			tail -n $end_len ${statf} |		 	\
-			awk  '/^[[:digit:]]/{print $1","$2","$6} 	\
+			tail -n $end_len ${statf} |			\
+			awk  '/^[[:digit:]]/{print $1","$2","$6}	\
 			      /^page/{print "page per rpc,read,write"}  \
 			      /^rpcs/{print "rpcs,read,write"}		\
-			      /^offset/{print "offset, read,write"}' 	\
+			      /^offset/{print "offset, read,write"}'	\
 			>> $logdir/analyse_${type_name}.csv
 		fi
 	fi
@@ -506,8 +502,8 @@ gather_analyse()
 	local log_tarball=$1
 	local option=$2
 
-        debug "Entering gather_analyze()"
-    
+	debug "Entering gather_analyze()"
+
 	#validating option
 	if [ -z "$log_tarball" -o -r "$option" ]; then
 		usage;
@@ -521,7 +517,7 @@ gather_analyse()
 	shift
 
 	local date=`date +%F-%H-%M`
-	local logdir="analyse-${date}" 
+	local logdir="analyse-${date}"
 
 	mkdir -p ${TMP}/${logdir}
 	mkdir -p ${TMP}/${logdir}/tmp
@@ -552,8 +548,8 @@ gather_analyse()
 	$TAR ${TMP}/${logdir}.tar.gz ${TMP}/${logdir} 1>/dev/null 2>&1
 
 	echo "create analysed tarball ${TMP}/${logdir}.tar.gz"
-	
-        debug "Leaving gather_analyze()"
+
+	debug "Leaving gather_analyze()"
 }
 
 case $OPTION in
