LU-18135 scripts: bad iproute rt_tables path
ksocklnd-config fails in some distros where there is no config in
/etc/iproute2, but in /usr/share/iproute2.
To fix that and keep the distro files untouched, we copy rt_tables
into /etc/iproute2 and modify it.

Lustre-change: https://review.whamcloud.com/60250
Lustre-commit: ff5042c83b82056745d472cc495f70c82c1189cf

Fixes: 7f60b2b55 ("LU-17006 lnet: set up routes for going across subnets")
Test-Parameters: trivial clientdistro=el9.6 testlist=sanity-lnet
Signed-off-by: Cyril Bordage <cbordage@whamcloud.com>
Change-Id: I0d633241d5dc2a22715e6959c6628476874059a8
Reviewed-by: Serguei Smirnov <ssmirnov@whamcloud.com>
Reviewed-by: Andreas Dilger <adilger@whamcloud.com>
(cherry picked from commit ff5042c83b82056745d472cc495f70c82c1189cf)
Reviewed-on: https://review.whamcloud.com/c/fs/lustre-release/+/62414
Tested-by: jenkins <devops@whamcloud.com>
Reviewed-by: Oleg Drokin <green@whamcloud.com>
Tested-by: Maloo <maloo@whamcloud.com>

diff --git a/lustre/scripts/ksocklnd-config b/lustre/scripts/ksocklnd-config
--- a/lustre/scripts/ksocklnd-config
+++ b/lustre/scripts/ksocklnd-config
@@ -87,7 +87,20 @@ do
 	eval "${logcmd[@]}"
 done
 
-filename='/etc/iproute2/rt_tables'
+# iproute config dir can be found in /etc or in /usr/share
+# If found in /usr/share, we copy it into /etc to avoid modifying
+# distro-provided version
+rt_tables_path="/etc/iproute2/rt_tables"
+if [ ! -f "$rt_tables_path" ]; then
+	distro_path=/usr/share/iproute2/rt_tables
+	if [ ! -f $distro_path ]; then
+		echo "Error: rt_tables file cannot be found"
+		exit 1
+	fi
+	mkdir -p /etc/iproute2/
+	cp $distro_path $rt_tables_path
+fi
+
 n=1
 max_table_num=0
 while read line; do
@@ -120,14 +133,14 @@ while read line; do
 	done
 	#echo "Line No. $n : $line: $max_table_num"
 	n=$((n+1))
-done < $filename
+done < $rt_tables_path
 
 # add entries for unlisted interfaces
 for i in "${interfaces[@]}"
 do
 	if [[ ! " ${interfaces_listed[@]} " =~ " ${i} " ]]; then
 		max_table_num=$((max_table_num+1))
-		echo "$max_table_num $i" >> $filename
+		echo "$max_table_num $i" >> $rt_tables_path
 	fi
 done
 
