Land b1_2_smallfix onto b1_2 (20040616_1009) - allow clients to reconnect during replay (b=1742) - re-awaken ptlrpcd if new requests arrive during check_set (b=3554) - fix cond_resched (b=3554) - only evict unfinished clients after recovery (b=3515) - allow bulk resend, prevent data loss (b=3570) - remove extraneous obd dereference causing LASSERT failure (b=3334) - don't use get_cycles() when creating temp. files on the mds (b=3156) - hold i_sem when setting i_size in ll_extent_lock() (b=3564) - fix ksocknal_fmb_callback() error messages (b=2918)

diff --git a/lustre/scripts/lbuild b/lustre/scripts/lbuild
--- a/lustre/scripts/lbuild
+++ b/lustre/scripts/lbuild
@@ -20,6 +20,10 @@ SERIES=
 CONFIG=
 VERSION=
 
+RHBUILD=0
+LINUX26=0
+SUSEBUILD=0
+
 BASE_ARCH=
 BIGMEM_ARCHS=
 BOOT_ARCHS=
@@ -182,12 +186,12 @@ load_target()
 
     CONFIG_FILE="$TOPDIR/lustre/kernel_patches/kernel_configs/$CONFIG"
     [ -r "$CONFIG_FILE" ] || \
-	fatal 1 "Target $TARGET's config file $CONFIG missing from $TOPDIR/lustre/kernel_patches/kernel_configs/configs."
+	fatal 1 "Target $TARGET's config file $CONFIG missing from $TOPDIR/lustre/kernel_patches/kernel_configs/."
 
     if [ "$EXTRA_VERSION_save" ] ; then
 	EXTRA_VERSION="$EXTRA_VERSION_save"
     elif ! (( $RELEASE )) ; then
-	EXTRA_VERSION="${EXTRA_VERSION}-${TAG//_/}.${TIMESTAMP}"
+	EXTRA_VERSION="${EXTRA_VERSION}-${TAG}.${TIMESTAMP}"
     fi
     # EXTRA_VERSION=${EXTRA_VERSION//-/_}
 
@@ -195,7 +199,7 @@ load_target()
 
     BUILD_ARCHS=
     for arch in $(uniqify "$ALL_ARCHS") ; do
-	if [ -z "$TARGET_ARCHS" ] || echo "$TARGET_ARCHS" | grep -s "$arch" ; then
+	if [ -z "$TARGET_ARCHS" ] || echo "$TARGET_ARCHS" | grep "$arch" >/dev/null 2>/dev/null ; then
 	    BUILD_ARCHS="$BUILD_ARCHS $arch"
 	fi
     done
@@ -270,9 +274,11 @@ patch_linux()
     popd >/dev/null
     echo "Full patch has been saved in ${FULL_PATCH##*/}."
     echo "Replacing .config files..."
-    [ -d linux/configs ] || mkdir linux/configs
+    [ -d linux/configs ] || mkdir linux/configs || \
+        fatal 1 "Error creating configs directory."
     rm -f linux/configs/*
-    cp -v lustre/kernel_patches/kernel_configs/kernel-${VERSION}-${TARGET}*.config linux/configs/
+    cp -v lustre/kernel_patches/kernel_configs/kernel-${VERSION}-${TARGET}*.config linux/configs/ || \
+	fatal 1 "Error copying in kernel configs."
 }
 
 pack_linux()
@@ -310,6 +316,8 @@ prep_build()
 	-e "s/@SMP_ARCHS@/$SMP_ARCHS/g" \
 	-e "s/@UP_ARCHS@/$UP_ARCHS/g" \
 	-e "s/@RHBUILD@/$RHBUILD/g" \
+	-e "s/@LINUX26@/$LINUX26/g" \
+	-e "s/@SUSEBUILD@/$SUSEBUILD/g" \
 	< $TOPDIR/lustre/scripts/lustre-kernel-2.4.spec.in \
 	> lustre-kernel-2.4.spec
     [ -d SRPMS ] || mkdir SRPMS
