- support for newer sles 9 sp 1 kernel  - fixes for building on ppc, ia64  - merge the full frame pointer fixes from llnl

diff --git a/lustre/scripts/lbuild b/lustre/scripts/lbuild
--- a/lustre/scripts/lbuild
+++ b/lustre/scripts/lbuild
@@ -24,7 +24,7 @@ RHBUILD=0
 LINUX26=0
 SUSEBUILD=0
 
-BASE_ARCH=
+BASE_ARCHS=
 BIGMEM_ARCHS=
 BOOT_ARCHS=
 JENSEN_ARCHS=
@@ -170,7 +170,7 @@ load_target()
     . "$TARGET_FILE"
 
     [ "$KERNEL"  ] || fatal 1 "Target $TARGET did not specify a kernel."
-    [ "$SERIES"  ] || fatal 1 "Target $TARGET did not specify a kernel patch series."
+#    [ "$SERIES"  ] || fatal 1 "Target $TARGET did not specify a kernel patch series."
 #    [ "$CONFIG"  ] || fatal 1 "Target $TARGET did not specify a kernel config."
     [ "$VERSION" ] || fatal 1 "Target $TARGET did not specify a kernel version."
 
@@ -180,9 +180,11 @@ load_target()
 	    fatal 1 "Target $TARGET's kernel file $KERNEL not found in kernel directory $KERNELDIR."
     fi
 
-    SERIES_FILE="$TOPDIR/lustre/kernel_patches/series/$SERIES"
-    [ -r "$SERIES_FILE" ] || \
-	fatal 1 "Target $TARGET's series $SERIES missing from $TOPDIR/lustre/kernel_patches/series."
+    if [ "$SERIES" ] ; then
+        SERIES_FILE="$TOPDIR/lustre/kernel_patches/series/$SERIES"
+        [ -r "$SERIES_FILE" ] || \
+	    fatal 1 "Target $TARGET's series $SERIES missing from $TOPDIR/lustre/kernel_patches/series."
+    fi
 
     CONFIG_FILE="$TOPDIR/lustre/kernel_patches/kernel_configs/$CONFIG"
     [ -r "$CONFIG_FILE" ] || \
@@ -257,6 +259,7 @@ unpack_linux()
 
 patch_linux()
 {
+    [ "$SERIES" ] || return 0
     FULL_PATCH="$PWD/lustre-kernel-${TARGET}-${EXTRA_VERSION}.patch"
     [ -f "$FULL_PATCH" ] && rm -f "$FULL_PATCH"
     pushd linux >/dev/null
@@ -302,6 +305,11 @@ clean_linux()
 prep_build()
 {
     # make .spec file
+    if [ -f /etc/init.d/functions -a -f /etc/sysconfig/network ] ; then
+        ENABLE_INIT_SCRIPTS=""
+    else
+        ENABLE_INIT_SCRIPTS="# "
+    fi
     sed -e "s/@KERNEL_VERSION@/$VERSION/g" \
 	-e "s/@KERNEL_EXTRA_VERSION@/$EXTRA_VERSION/g" \
 	-e "s^@KERNEL_RELEASE@^${EXTRA_VERSION//-/_}^g" \
@@ -318,6 +326,7 @@ prep_build()
 	-e "s/@RHBUILD@/$RHBUILD/g" \
 	-e "s/@LINUX26@/$LINUX26/g" \
 	-e "s/@SUSEBUILD@/$SUSEBUILD/g" \
+	-e "s/@ENABLE_INIT_SCRIPTS@/$ENABLE_INIT_SCRIPTS/g" \
 	< $TOPDIR/lustre/scripts/lustre-kernel-2.4.spec.in \
 	> lustre-kernel-2.4.spec
     [ -d SRPMS ] || mkdir SRPMS
diff --git a/lustre/scripts/lmake b/lustre/scripts/lmake
--- a/lustre/scripts/lmake
+++ b/lustre/scripts/lmake
@@ -27,7 +27,7 @@ CONFIG=
 VERSION=
 EXTRA_VERSION=
 
-BASE_ARCH=
+BASE_ARCHS=
 BIGMEM_ARCHS=
 BOOT_ARCHS=
 JENSEN_ARCHS=
@@ -40,7 +40,6 @@ TARGET_FILE=
 KERNEL_FILE=
 SERIES_FILE=
 CONFIG_FILE=
-CC=${CC:-gcc}
 
 canon()
 {
@@ -194,7 +193,8 @@ load_target()
     . "$TARGET_FILE"
 
     [ "$KERNEL" ] || fatal 1 "Target $TARGET did not specify a kernel."
-    [ "$SERIES" ] || fatal 1 "Target $TARGET did not specify a patch series."
+# Suse 2.6 has our patches in already
+#    [ "$SERIES" ] || fatal 1 "Target $TARGET did not specify a patch series."
 #    [ "$CONFIG" ] || fatal 1 "Target $TARGET did not specify a kernel config."
     [ "$VERSION" ] || fatal 1 "Target $TARGET did not specify the kernel version."
     
@@ -204,9 +204,11 @@ load_target()
 	    fatal 1 "Target $TARGET's kernel file $KERNEL not found in kernel directory $KERNELDIR."
     fi
 
-    SERIES_FILE="$TOPDIR/kernel_patches/series/$SERIES"
-    [ -r "$SERIES_FILE" ] || \
-	fatal 1 "Target $TARGET's series $SERIES missing from $TOPDIR/kernel_patches/series."
+    if [ "$SERIES" ]; then
+        SERIES_FILE="$TOPDIR/kernel_patches/series/$SERIES"
+        [ -r "$SERIES_FILE" ] || \
+	    fatal 1 "Target $TARGET's series $SERIES missing from $TOPDIR/kernel_patches/series."
+    fi
 
     TARGET_ARCH=${TARGET_ARCH:-$BASE_ARCHS}
     CONFIG_TARGET="$TARGET-${TARGET_ARCH}${TARGET_CONFIG:+-$TARGET_CONFIG}"
@@ -262,6 +264,7 @@ extract_kernel()
 patch_kernel()
 {
     (( $UNPACK_KERNEL )) || return 0
+    [ "$SERIES" ] || return 0
     pushd "$TOPDIR/linux" >/dev/null
     echo -n "Applying patch"
     for patch in $(<"$SERIES_FILE") ; do
@@ -277,15 +280,18 @@ patch_kernel()
 
 set_make()
 {
-    MAKE="make -s CC=$CC"
+    MAKE="make -s"
+    if [ "$CC" ] ; then
+	MAKE="$MAKE CC=$CC"
+    fi
     if [ "$ARCH" ] ; then
-	MAKE="$MAKE ARCH=$ARCH"
+	MAKE_ARCH="$MAKE ARCH=$ARCH"
     else
 	case $TARGET_ARCH in
 	    i?86)
                 ;;
             *)
-	        MAKE="$MAKE ARCH=$TARGET_ARCH"
+	        MAKE_ARCH="$MAKE ARCH=$TARGET_ARCH"
 		;;
         esac
     fi
@@ -326,13 +332,14 @@ depend_kernel()
 build_kernel()
 {
     (( $BUILD_KERNEL )) || return 0
-    # we need to override $CC at make time, since there is no
-    # configure
     set_make
     echo "Building kernel in $PWD..."
     case "$TARGET_ARCH" in
 	i386 | i586 | i686 | athlon | x86_64)
 	    $MAKE_J bzImage || fatal 1 "Error making bzImage."
+	    ;;
+        ppc | ppc64)
+	    $MAKE_J vmlinux || fatal 1 "Error making vmlinux."
 	    ;;
 	*)
 	    $MAKE_J boot || fatal 1 "Error making boot."
@@ -366,6 +373,7 @@ build_lustre()
 install_kernel()
 {
     (( $INSTALL_KERNEL )) || return 0
+    set_make
     FULL_VERSION="${VERSION}-${EXTRA_VERSION}${TARGET_CONFIG}"
     pushd "$TOPDIR/linux" >/dev/null
     mkdir -p "$DESTDIR/boot"
@@ -377,7 +385,7 @@ install_kernel()
     mkdir -p "$DESTDIR/dev/shm"
     mkdir -p "$DESTDIR/lib/modules/${FULL_VERSION}"
 
-    make CC="$CC" INSTALL_MOD_PATH="$DESTDIR" KERNELRELEASE="$FULL_VERSION" \
+    $MAKE INSTALL_MOD_PATH="$DESTDIR" KERNELRELEASE="$FULL_VERSION" \
 	-s modules_install || \
 	fatal 1 "Error installing modules."
 
@@ -392,12 +400,16 @@ install_kernel()
 	    cp vmlinux "$DESTDIR/lib/modules/${FULL_VERSION}/"
 	    ln -sf "../lib/modules/${FULL_VERSION}/vmlinux" "$DESTDIR/boot/vmlinux-${FULL_VERSION}"
 	    ;;
+        ppc | ppc64)
+	    cp vmlinux "$DESTDIR/boot/vmlinux-${FULL_VERSION}"
+	    ln -sf "$DESTDIR/boot/vmlinux-${FULL_VERSION}" "../lib/modules/${FULL_VERSION}/vmlinux" 
+	    ;;
 	ia64)
 	    gzip -cfv vmlinux > vmlinuz
 	    mkdir -p "$DESTDIR/boot/efi/redhat"
 	    install -m 755 vmlinux "$DESTDIR/lib/modules/${FULL_VERSION}/"
 	    install -m 755 vmlinuz "$DESTDIR/boot/efi/redhat/vmlinuz-${FULL_VERSION}"
-	    ln -sf "../lib/modules/${FULL_VERSION}/vmlinux" "$DESTDIR/boot/efi/redhat/vmlinux-${FULL_VERSION}"
+	    ln -sf "../../../lib/modules/${FULL_VERSION}/vmlinux" "$DESTDIR/boot/efi/redhat/vmlinux-${FULL_VERSION}"
 	    ln -sf "efi/redhat/vmlinux-${FULL_VERSION}" "$DESTDIR/boot/vmlinux-${FULL_VERSION}"
 	    ln -sf "efi/redhat/vmlinuz-${FULL_VERSION}" "$DESTDIR/boot/vmlinuz-${FULL_VERSION}"
 	    ;;
