LU-2445 utils: lfs migrate support
Add a new command migrate to lfs utility.
migrate takes sames args as setstripe and a --block option
It:
- create a volatile file based on new stripe information
- copy file data to this volatile file
- swap the 2 layouts
- if --block is set, take the grouplock to block other access
  during copy

So after migrate the file is restriped (mtime, atime are not
changed).
lfs_migrate is also updated to use the new call and
keeps the rsync mode as a fallback.

Signed-off-by: JC Lafoucriere <jacques-charles.lafoucriere@cea.fr>
Change-Id: I96bafb0be9bc273295c4c900c65b4028864fcbaa
Reviewed-on: http://review.whamcloud.com/5620
Tested-by: Hudson
Reviewed-by: Jinshan Xiong <jinshan.xiong@intel.com>
Tested-by: Maloo <whamcloud.maloo@gmail.com>
Reviewed-by: Andreas Dilger <andreas.dilger@intel.com>

diff --git a/lustre/scripts/lfs_migrate b/lustre/scripts/lfs_migrate
--- a/lustre/scripts/lfs_migrate
+++ b/lustre/scripts/lfs_migrate
@@ -101,6 +101,8 @@ umask 0077
 $LFS getstripe --help 2>&1 | grep -q stripe-size && LFS_SIZE_OPT="-S"
 
 lfs_migrate() {
+	local RSYNC_MODE=false
+
 	while IFS='' read -d '' OLDNAME; do
 		$ECHO -n "$OLDNAME: "
 
@@ -130,7 +132,6 @@ lfs_migrate() {
 			continue
 		fi
 
-
 		if [ "$OPT_RESTRIPE" ]; then
 			UNLINK=""
 		else
@@ -147,6 +148,19 @@ lfs_migrate() {
 
 			[ -z "$COUNT" -o -z "$SIZE" ] && UNLINK=""
 		fi
+
+		# first try to migrate inside lustre
+		# if failed go back to old rsync mode
+		if [[ $RSYNC_MODE == false ]]; then
+			$LFS migrate -c${COUNT} ${LFS_SIZE_OPT}${SIZE} $OLDNAME
+			if [[ $? == 0 ]]; then
+				$ECHO "done"
+				continue
+			else
+				RSYNC_MODE=true
+			fi
+		fi
+
 		NEWNAME=$(mktemp $UNLINK "$OLDNAME.tmp.XXXXXX")
 		if [ $? -ne 0 -o -z "$NEWNAME" ]; then
 			echo -e "\r$OLDNAME: can't make temp file, skipped" 1>&2
