smash the HEAD with the contents of b_cmd.  HEAD_PRE_CMD_SMASH and cMD_PRE_CMD_SMASH are the relevant tags.
The pre-smashing contents of HEAD will be committed by yury into b_cmd as a
merge of the two branches.  These will be stabilized on b_cmd and eventually
landed onto HEAD.

diff --git a/lustre/scripts/lmake b/lustre/scripts/lmake
--- a/lustre/scripts/lmake
+++ b/lustre/scripts/lmake
@@ -275,34 +275,20 @@ patch_kernel()
     popd >/dev/null
 }
 
-set_make()
-{
-    MAKE="make -s CC=$CC"
-    if [ "$ARCH" ] ; then
-	MAKE="$MAKE ARCH=$ARCH"
-    fi
-    MAKE_J="$MAKE -j $JOBS"
-}
-
 depend_kernel()
 {
     (( $DEPEND_KERNEL )) || return 0
     # we need to override $CC at make time, since there is no
     # configure
-    set_make
+    MAKE="make -s CC=$CC"
     pushd "$TOPDIR/linux" >/dev/null
     echo "Overriding EXTRAVERSION in kernel..."
     perl -p -i -e "s/^EXTRAVERSION.*/EXTRAVERSION = -${EXTRA_VERSION}${TARGET_CONFIG}/" Makefile
     echo "Making depend in $PWD..."
     $MAKE mrproper || fatal 1 "Error running make mrproper"
     cp "$CONFIG_FILE" .config
-    if grep -q oldconfig_nonint Makefile ; then
-	OLDCONFIG='oldconfig_nonint'
-    else
-	OLDCONFIG='oldconfig'
-    fi
-    $MAKE $OLDCONFIG || fatal 1 "Error running make oldconfig"
-    $MAKE_J dep || fatal 1 "Error running make dep"
+    $MAKE oldconfig_nonint || fatal 1 "Error running make oldconfig"
+    $MAKE -j $JOBS dep || fatal 1 "Error running make dep"
     $MAKE include/linux/version.h || fatal 1 "Error making include/linux/version.h"
 }
 
@@ -311,17 +297,17 @@ build_kernel()
     (( $BUILD_KERNEL )) || return 0
     # we need to override $CC at make time, since there is no
     # configure
-    set_make
+    MAKE="make -s CC=$CC"
     echo "Building kernel in $PWD..."
     case "$TARGET_ARCH" in
 	i386 | i586 | i686 | athlon | x86_64)
-	    $MAKE_J bzImage || fatal 1 "Error making bzImage."
+	    $MAKE -j $JOBS -s bzImage || fatal 1 "Error making bzImage."
 	    ;;
 	*)
-	    $MAKE_J boot || fatal 1 "Error making boot."
+	    $MAKE -j $JOBS -s boot || fatal 1 "Error making boot."
 	    ;;
     esac
-    $MAKE_J modules || fatal 1 "Error building modules."
+    $MAKE -j $JOBS -s modules || fatal 1 "Error building modules."
 
     popd >/dev/null
 }
@@ -340,9 +326,8 @@ configure_lustre()
 build_lustre()
 {
     (( $BUILD_LUSTRE )) || return 0
-    set_make
     pushd "$TOPDIR" >/dev/null
-    $MAKE_J || fatal 1 "Error building Lustre."
+    make -j $JOBS -s || fatal 1 "Error building Lustre."
     popd >/dev/null
 }
 
