LU-1935 scripts: don't generate lustre init script
An "overriding commands for target `lustre'" build warning resulted
from the addition of lustre to the genscripts Makefile variable.  In
fact the genscripts processing is superfluous for the lustre script,
so we could just fix the warning by removing it.  However, generating
the script from a .in file seems unnecessarily complicated, so this
change goes a step further by making the script static.  It now
detects at run-time whether to use the ldiskfsprogs or the e2fsprogs
utilities, instead of using autoconf macros to encode it at build
time.

Signed-off-by: Ned Bass <bass6@llnl.gov>
Change-Id: Ie000a87adabbc2a001ed9ff2f5750041a5abea5b
Reviewed-on: http://review.whamcloud.com/4015
Tested-by: Hudson
Tested-by: Maloo <whamcloud.maloo@gmail.com>
Reviewed-by: Andreas Dilger <adilger@whamcloud.com>
Reviewed-by: Alex Zhuravlev <bzzz@whamcloud.com>

diff --git a/lustre/scripts/lustre b/lustre/scripts/lustre
--- a/lustre/scripts/lustre
+++ b/lustre/scripts/lustre
@@ -8,6 +8,8 @@
 # probe: true
 # config: /etc/sysconfig/lustre
 
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+
 # Source function library.
 . /etc/rc.d/init.d/functions
 
@@ -40,6 +42,20 @@ ZPOOL_LAYOUT_PORTS=${ZPOOL_LAYOUT_PORTS:-""}
 ZPOOL_LAYOUT_MAP=${ZPOOL_LAYOUT_MAP:-""}
 MOUNT_DELAY=${MOUNT_DELAY:-2}
 LOAD_ZFS=${LOAD_ZFS:-""}
+
+if [ -z "$TUNE2FS" ] ; then
+	TUNE2FS=`which tunefs.ldiskfs 2>/dev/null`
+	if [ -z "$TUNE2FS" ] ; then
+		TUNE2FS=`which tune2fs 2>/dev/null`
+	fi
+fi
+
+if [ -z "$PFSCK" ] ; then
+	PFSCK=`which pfsck.ldiskfs 2>/dev/null`
+	if [ -z "$PFSCK" ] ; then
+		PFSCK=`which fsck 2>/dev/null`
+	fi
+fi
 
 shopt -s nullglob
 
@@ -180,15 +196,15 @@ fsck_test ()
 	devices=`echo $devices |xargs -n 1|grep '^/'|xargs`
 
 	if [ -n "${FSCK_ARGS}" -a -n "$devices" ]; then
-		if [ -x /sbin/@PFSCK@ ] ; then
-			echo "@PFSCK@ $devices -- ${FSCK_ARGS}"
-			/sbin/@PFSCK@ $devices -- ${FSCK_ARGS}
+		if [ -x $PFSCK ] ; then
+			echo "$PFSCK $devices -- ${FSCK_ARGS}"
+			$PFSCK $devices -- ${FSCK_ARGS}
 			if [ $? -ne 0 -a $? -ne 1 ] ; then
-				echo "FAILED: @PFSCK@ -- ${FSCK_ARGS}: $?"
+				echo "FAILED: $PFSCK -- ${FSCK_ARGS}: $?"
 				return 1
 			fi
 		else
-			echo "/sbin/@PFSCK@ not found"
+			echo "$PFSCK not found"
 			return 1
 		fi
 	fi
@@ -203,7 +219,7 @@ test_feature_flag()
 	local result=1
 	local feature
 
-	for feature in `/sbin/@TUNE2FS@ -l $dev 2>/dev/null \
+	for feature in `$TUNE2FS -l $dev 2>/dev/null \
 				| grep features: | sed -e 's/^.*: //'`; do
 		if [ "$feature" == "$flag" ]; then
 			result=0
@@ -222,13 +238,13 @@ mmp_test ()
 	local result=0
 
 	if [ "$REQUIRE_MMP_FEATURE" == "yes" ]; then
-		if [ -x /sbin/@TUNE2FS@ ]; then
+		if [ -x $TUNE2FS ]; then
 			if ! test_feature_flag $dev "mmp"; then
 				echo "mmp feature flag is not set on $dev"
 				result=1
 			fi
 		else
-			echo "/sbin/@TUNE2FS@ not found"
+			echo "$TUNE2FS not found"
 			result=1
 		fi
 	fi
