LU-19859 scripts: Use actual bash binary
Replace #!/bin/bash with #!/usr/bin/bash in scripts to avoid conflicts with
/bin/sh on RHEL 9. Also replace #!/bin/sh with #!/usr/bin/bash in scripts
shebangs because /bin/sh is not always bash.

Change-Id: Ibad5c2e7226df3fffa24faa1777074c23067b18f
Signed-off-by: Nikos Papakonstantinou <npapakonstantinou@ddn.com>
Reviewed-on: https://review.whamcloud.com/c/fs/lustre-release/+/64112
Reviewed-by: Andreas Dilger <adilger@thelustrecollective.com>
Tested-by: Maloo <maloo@whamcloud.com>
Reviewed-by: Arshad Hussain <arshad.hussain@aeoncomputing.com>
Reviewed-by: Oleg Drokin <green@whamcloud.com>
Tested-by: jenkins <devops@whamcloud.com>

diff --git a/lustre/tests/kbuild b/lustre/tests/kbuild
--- a/lustre/tests/kbuild
+++ b/lustre/tests/kbuild
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /usr/bin/bash
 # SPDX-License-Identifier: GPL-2.0-only
 
 #
@@ -240,7 +240,7 @@ export CCACHE_DIR=$ccache_dir
 
 cd $tgt || fail 4 "Cannot cd into $tgt"
 
-echo '#! /bin/sh'   >  $cc_script || fail 5 "Cannot write into $cc_script"
+echo '#! /usr/bin/bash'   >  $cc_script || fail 5 "Cannot write into $cc_script"
 echo 'ccache cc $*' >> $cc_script || fail 6 "Cannot append to $cc_script"
 chmod u+rx $cc_script || fail 7 "Cannot chmod u+rx $cc_script"
 
