Add some renames to the runtest, since nobody seems to have noticed that it didn't work.

diff --git a/lustre/tests/runtests b/lustre/tests/runtests
--- a/lustre/tests/runtests
+++ b/lustre/tests/runtests
@@ -21,44 +21,57 @@ setup_opts $@
 # let's start slowly here...
 echo "touching $OSCMT"
 touch $OSCMT || fail "can't touch $OSCMT" 2
-echo "copying /etc/hosts to $OSCMT/hosts"
-cp /etc/hosts $OSCMT || fail "can't cp /etc/hosts to $OSCMT/hosts" 3
-echo "comparing /etc/hosts and $OSCMT/hosts"
-diff -u /etc/hosts $OSCMT/hosts || fail "$OSCMT/hosts different" 4
+HOSTS=$OSCMT/hosts.$$
+echo "copying /etc/hosts to $HOSTS"
+cp /etc/hosts $HOSTS || fail "can't cp /etc/hosts to $HOSTS" 3
+echo "comparing /etc/hosts and $HOSTS"
+diff -u /etc/hosts $HOSTS || fail "$HOSTS different" 4
+echo "renaming $HOSTS to $HOSTS.ren"
+mv $HOSTS $HOSTS.ren || fail "can't rename $HOSTS to $HOSTS.ren" 5
+echo "copying /etc/hosts to $HOSTS again"
+cp /etc/hosts $HOSTS || fail "can't cp /etc/hosts to $HOSTS again" 6
+echo "truncating $HOSTS"
+> $HOSTS || fail "can't truncate $HOSTS" 8
+echo "removing $HOSTS"
+rm $HOSTS || fail "can't remove $HOSTS" 9
+
+DST=$OSCMT/runtest.$$
+# let's start slowly here...
+echo "creating $DST"
+mkdir $DST || fail "can't mkdir $DST" 10
 
 # ok, that hopefully worked, so let's do a little more
 FILES=`find $SRC -type f | head -$COUNT`
-echo "copying files from $SRC to $OSCMT$SRC"
-tar cf - $FILES | tar xvf - -C $OSCMT || fail "copying $SRC" 10
+echo "copying files from $SRC to $DST$SRC"
+tar cf - $FILES | tar xvf - -C $DST || fail "copying $SRC" 11
 
 echo "comparing newly copied files"
 for f in $FILES; do
-	diff -q $f $OSCMT/$f || ERROR=11
+	diff -q $f $DST/$f || ERROR=11
 done
 
-[ "$ERROR" ] && fail "old and new files are different" 11
+[ "$ERROR" ] && fail "old and new files are different" $ERROR
 
 sh llcleanup.sh $@
 
 echo | sh llrsetup.sh $@ || exit 20
 echo "comparing previously copied files"
-diff -u /etc/hosts $OSCMT/hosts || fail "$OSCMT/hosts is now different" 21
-
 for f in $FILES; do
-	diff -q $f $OSCMT/$f || ERROR=22
+	diff -q $f $DST/$f || ERROR=22
 done
 
-[ "$ERROR" ] && fail "old and new files are different on second diff" 23
+[ "$ERROR" ] && fail "old and new files are different on second diff" $ERROR
 
 sh llcleanup.sh $@
-echo | sh llrsetup.sh $@ || exit 24
+echo | sh llrsetup.sh $@ || exit 31
 
-echo "truncating $OSCMT/hosts"
-> $OSCMT/hosts || fail "can't truncate $OSTMT/hosts" 25
-echo "removing $OSCMT/hosts"
-rm $OSCMT/hosts || fail "can't remove $OSCMT/hosts" 26
-
-echo "removing $OSCMT$SRC"
-rm -r $OSCMT$SRC || fail "can't remove $OSCMT$SRC" 27
+echo "renaming $HOSTS.ren to $HOSTS"
+mv $HOSTS.ren $HOSTS || fail "can't rename $HOSTS.ren to $HOSTS" 32
+echo "truncating $HOSTS"
+> $HOSTS || fail "can't truncate $HOSTS" 34
+echo "removing $HOSTS"
+rm $HOSTS || fail "can't remove $HOSTS again" 36
+echo "removing $DST"
+rm -r $DST || fail "can't remove $DST" 37
 
 sh llcleanup.sh $@
