*  Merged b_devel updates

diff --git a/lustre/tests/runtests b/lustre/tests/runtests
--- a/lustre/tests/runtests
+++ b/lustre/tests/runtests
@@ -35,41 +35,42 @@ while [ "$1" ]; do
 	shift
 done
 
-OSCMT="`mount | awk '/ lustre_lite / { print $3 }' | tail -1`"
-if [ -z "$OSCMT" ]; then
+MOUNT="`mount | awk '/ lustre_lite / { print $3 }' | tail -1`"
+if [ -z "$MOUNT" ]; then
 	sh llmount.sh
-	OSCMT="`mount | awk '/ lustre_lite / { print $3 }' | tail -1`"
-	[ -z "$OSCMT" ] && fail "no lustre filesystem mounted" 1
+	MOUNT="`mount | awk '/ lustre_lite / { print $3 }' | tail -1`"
+	[ -z "$MOUNT" ] && fail "no lustre filesystem mounted" 1
 	I_MOUNTED="yes"
 fi
 
-OSCTMP=`echo $OSCMT | tr "/" "."`
+OSCTMP=`echo $MOUNT | tr "/" "."`
 USED=`df | awk "/$OSCTMP/ { print \\$3 }" | tail -1`
 USED=`expr $USED + 16`	# Some space for the status file
 
 # let's start slowly here...
-log "touching $OSCMT"
-touch $OSCMT || fail "can't touch $OSCMT" 2
-HOSTS=$OSCMT/hosts.$$
+log "touching $MOUNT"
+touch $MOUNT || fail "can't touch $MOUNT" 2
+HOSTS=$MOUNT/hosts.$$
 
-# this will cause the following cp to trigger bug #620096
-log "create an empty file $HOSTS"
-mcreate $HOSTS
+if [ $COUNT -gt 10 -o $COUNT -eq 0 ]; then
+	# this will cause the following cp to trigger bug #620096
+	log "create an empty file $HOSTS"
+	mcreate $HOSTS
+	log "copying /etc/hosts to $HOSTS"
+	cp /etc/hosts $HOSTS || fail "can't cp /etc/hosts to $HOSTS" 3
+	log "comparing /etc/hosts and $HOSTS"
+	diff -u /etc/hosts $HOSTS || fail "$HOSTS different" 4
+	log "renaming $HOSTS to $HOSTS.ren"
+	mv $HOSTS $HOSTS.ren || fail "can't rename $HOSTS to $HOSTS.ren" 5
+	log "copying /etc/hosts to $HOSTS again"
+	cp /etc/hosts $HOSTS || fail "can't cp /etc/hosts to $HOSTS again" 6
+	log "truncating $HOSTS"
+	> $HOSTS || fail "can't truncate $HOSTS" 8
+	log "removing $HOSTS"
+	rm $HOSTS || fail "can't remove $HOSTS" 9
+fi
 
-log "copying /etc/hosts to $HOSTS"
-cp /etc/hosts $HOSTS || fail "can't cp /etc/hosts to $HOSTS" 3
-log "comparing /etc/hosts and $HOSTS"
-diff -u /etc/hosts $HOSTS || fail "$HOSTS different" 4
-log "renaming $HOSTS to $HOSTS.ren"
-mv $HOSTS $HOSTS.ren || fail "can't rename $HOSTS to $HOSTS.ren" 5
-log "copying /etc/hosts to $HOSTS again"
-cp /etc/hosts $HOSTS || fail "can't cp /etc/hosts to $HOSTS again" 6
-log "truncating $HOSTS"
-> $HOSTS || fail "can't truncate $HOSTS" 8
-log "removing $HOSTS"
-rm $HOSTS || fail "can't remove $HOSTS" 9
-
-DST=$OSCMT/runtest.$$
+DST=$MOUNT/runtest.$$
 # let's start slowly here...
 log "creating $DST"
 mkdir $DST || fail "can't mkdir $DST" 10
@@ -102,27 +103,29 @@ done
 sh llmountcleanup.sh || exit 19
 sh llrmount.sh || exit 20
 
-log "renaming $HOSTS.ren to $HOSTS"
-mv $HOSTS.ren $HOSTS || fail "can't rename $HOSTS.ren to $HOSTS" 32
-log "truncating $HOSTS"
-> $HOSTS || fail "can't truncate $HOSTS" 34
-log "removing $HOSTS"
-rm $HOSTS || fail "can't remove $HOSTS again" 36
 log "removing $DST"
 rm -r $V $DST || fail "can't remove $DST" 37
 
+if [ $COUNT -gt 10 -o $COUNT -eq 0 ]; then
+	log "renaming $HOSTS.ren to $HOSTS"
+	mv $HOSTS.ren $HOSTS || fail "can't rename $HOSTS.ren to $HOSTS" 32
+	log "truncating $HOSTS"
+	> $HOSTS || fail "can't truncate $HOSTS" 34
+	log "removing $HOSTS"
+	rm $HOSTS || fail "can't remove $HOSTS again" 36
+fi
+
 # mkdirmany test (bug 589)
-log "running mkdirmany $OSCMT/base$$ 100"
-$MKDIRMANY $OSCMT/base$$ 100 || fail "mkdirmany failed"
+log "running mkdirmany $MOUNT/base$$ 100"
+$MKDIRMANY $MOUNT/base$$ 100 || fail "mkdirmany failed"
 log "removing mkdirmany directories"
-rmdir $OSCMT/base$$* || fail "mkdirmany cleanup failed"
+rmdir $MOUNT/base$$* || fail "mkdirmany cleanup failed"
 
 log "done"
 
 NOWUSED=`df | awk "/$OSCTMP/ { print \\$3 }" | tail -1`
-if [ $NOWUSED -gt $USED ]; then
+if [ `expr $NOWUSED - $USED` -gt 1024 ]; then
 	echo "Space not all freed: now ${NOWUSED}kB, was ${USED}kB." 1>&2
-	echo "This is normal on BA OSTs, because of subdirectories." 1>&2
 fi
 
 if [ "$I_MOUNTED" = "yes" ]; then
