LU-1538 tests: clean up runtests code style
Use $(...) instead of `...` for sub-shells.
Improve some error messages and code style.
Use $DIR/$tdir for tests instead of $MOUNT/$$.

Test-Parameters: envdefinitions=SLOW=yes  testlist=runtests
Signed-off-by: Andreas Dilger <andreas.dilger@intel.com>
Change-Id: I4f3eb4a3e288c6fc45ae6ef1fb2008e8e6babe84
Reviewed-on: http://review.whamcloud.com/5739
Tested-by: Hudson
Tested-by: Maloo <whamcloud.maloo@gmail.com>
Reviewed-by: Bob Glossman <bob.glossman@intel.com>
Reviewed-by: Emoly Liu <emoly.liu@intel.com>
Reviewed-by: Oleg Drokin <oleg.drokin@intel.com>

diff --git a/lustre/tests/runtests b/lustre/tests/runtests
--- a/lustre/tests/runtests
+++ b/lustre/tests/runtests
@@ -4,8 +4,8 @@
 # Probably a good idea to run this before doing any checkins.
 # In the future this can become more fancy, but it's OK for now.
 
-LUSTRE=${LUSTRE:-`dirname $0`/..}
-SRCDIR="`dirname $0`"
+LUSTRE=${LUSTRE:-$(dirname $0)/..}
+SRCDIR="$(dirname $0)"
 export PATH=/sbin:/usr/sbin:$SRCDIR:$SRCDIR/../utils:$PATH
 
 export NAME=${NAME:-local}
@@ -22,18 +22,18 @@ RUNTESTS_SRC=${RUNTESTS_SRC:-"/etc /bin"}
 [ "$MCREATE" ] || MCREATE=mcreate
 
 [ "$MKDIRMANY" ] || MKDIRMANY="createmany -d"
+[ "$RMDIRMANY" ] || RMDIRMANY="unlinkmany -d"
 
 check_and_setup_lustre
 test_1() {
-OSCTMP=`echo $MOUNT | tr "/" "."`
-USED=`df | awk "/$OSCTMP/ { print \\$3 }" | tail -n 1`
-USED=`expr $USED + 16`	# Some space for the status file
+# Include some extra space for the status file
+USED=$(df -P $DIR | awk '{ print $3 }' | tail -n 1)
 
 # let's start slowly here...
-START=`date +%s`
-log "touching $MOUNT at `date`"
-touch $MOUNT || error "can't touch $MOUNT" 2
-HOSTS=$MOUNT/hosts.$$
+START=$(date +%s)
+log "touching $DIR at $(date) (@$START)"
+touch $DIR || error "can't touch $DIR" 2
+HOSTS=$DIR/hosts.$$
 TRUNCSIZE=123
 
 if [ $COUNT -gt 10 -o $COUNT -eq 0 ]; then
@@ -52,15 +52,18 @@ if [ $COUNT -gt 10 -o $COUNT -eq 0 ]; then
 	> $HOSTS || error "can't truncate $HOSTS" 8
 	log "removing $HOSTS"
 	rm $HOSTS || error "can't remove $HOSTS" 9
+	log "copying /etc/hosts to $HOSTS.2"
 	cp /etc/hosts $HOSTS.2 || error "can't cp /etc/hosts to $HOSTS.2" 7
 	log "truncating $HOSTS.2 to $TRUNCSIZE bytes"
-	$TRUNCATE $HOSTS.2 $TRUNCSIZE
+	$TRUNCATE $HOSTS.2 $TRUNCSIZE || error "can't truncate $HOSTS.2" 10
+	checkstat -s $TRUNCSIZE $HOSTS.2 ||
+		error "$HOSTS.2 isn't $TRUNCSIZE bytes" 11
 fi
 
-DST=$MOUNT/runtest.$$
+DST=$DIR/$tdir
 # let's start slowly here...
 log "creating $DST"
-mkdir $DST || error "can't mkdir $DST" 10
+test_mkdir -p $DST || error "can't mkdir $DST" 12
 
 # ok, that hopefully worked, so let's do a little more, with files that
 # haven't changed in the last day (hopefully they don't change during test)
@@ -71,19 +74,19 @@ find $RUNTESTS_SRC -type f -mtime +1 | head -n $COUNT | tr '\n' '\0' > $FILES
 	error "$RUNTESTS_SRC contains only files modifed less than 2 days ago"
 COUNT=$(xargs -0 -n 1 echo < $FILES | wc -l)
 
-log "copying $COUNT files from $RUNTESTS_SRC to $DST$RUNTESTS_SRC at `date`"
+log "copying $COUNT files from $RUNTESTS_SRC to $DST$RUNTESTS_SRC at $(date)"
 tar cf - --null --files-from $FILES | tar xvf - -C $DST > /dev/null ||
-	error "copying $RUNTESTS_SRC" 11
+	error "copying $RUNTESTS_SRC" 17
 
-log "comparing $COUNT newly copied files at `date`"
+log "comparing $COUNT newly copied files at $(date)"
 
 cat $FILES | tr "\0" "\n" | ( rc=0; while read f; do
 	[ $V ] && log "verifying $DST/$f"
-	diff -q "$f" "$DST/$f" || rc=11
+	diff -q "$f" "$DST/$f" || rc=18
 done
 [ "$rc" = 0 ] || error_exit "old and new files are different: rc=$rc" ) 
 
-log "finished at `date` ($(($(date +%s) - START)))"
+log "finished at $(date) ($(($(date +%s) - START)))"
 
 stopall || exit 19
 setupall || exit 20
@@ -115,16 +118,20 @@ if [ $COUNT -gt 10 -o $COUNT -eq 0 ]; then
 fi
 
 # mkdirmany test (bug 589)
-log "running $MKDIRMANY $MOUNT/base$$ 100"
-$MKDIRMANY $MOUNT/base$$ 100 || error "mkdirmany failed"
-log "removing $MKDIRMANY directories"
-rmdir $MOUNT/base$$* || error "mkdirmany cleanup failed"
+test_mkdir -p $DST
+log "running $MKDIRMANY $DST/d 100"
+$MKDIRMANY $DST/d 100 || error "$MKDIRMANY failed"
+log "running $RMDIRMANY $DST/d 100"
+$RMDIRMANY $DST/d 100 || error "$RMDIRMANY cleanup failed"
 
 log "done"
 
-NOWUSED=`df | awk "/$OSCTMP/ { print \\$3 }" | tail -n 1`
-if [ `expr $NOWUSED - $USED` -gt 1024 ]; then
-	echo "Space not all freed: now ${NOWUSED}kB, was ${USED}kB." 1>&2
+wait_delete_completed
+NOWUSED=$(($(df -P $DIR | awk '{ print $3 }' | tail -n 1)))
+if [ $(expr $NOWUSED - $USED) -gt 1024 ]; then
+	error "Space not all freed: now ${NOWUSED}kB, was ${USED}kB."
+else
+	log "Space was freed: now ${NOWUSED}kB, was ${USED}kB."
 fi
 }
 run_test 1 "All Runtests"
