b=18804 o=Adilger i=grev t-f and tests remote_* nodsh cleanup

diff --git a/lustre/tests/runtests b/lustre/tests/runtests
--- a/lustre/tests/runtests
+++ b/lustre/tests/runtests
@@ -18,12 +18,6 @@ SETUP=${SETUP:-setupall}
 FORMAT=${FORMAT:-formatall}
 CLEANUP=${CLEANUP:-stopall}
 
-fail() { 
-	echo "ERROR: $1" 1>&2
-	[ $2 ] && RC=$2 || RC=1
-	exit $RC
-}
-
 ERROR=
 RUNTESTS_SRC=${RUNTESTS_SRC:-"/etc /bin"}
 [ "$COUNT" ] || COUNT=1000
@@ -59,7 +53,7 @@ USED=`expr $USED + 16`	# Some space for the status file
 # let's start slowly here...
 START=`date +%s`
 log "touching $MOUNT at `date`"
-touch $MOUNT || fail "can't touch $MOUNT" 2
+touch $MOUNT || error "can't touch $MOUNT" 2
 HOSTS=$MOUNT/hosts.$$
 TRUNCSIZE=123
 
@@ -68,18 +62,18 @@ if [ $COUNT -gt 10 -o $COUNT -eq 0 ]; then
 	log "create an empty file $HOSTS"
 	mcreate $HOSTS
 	log "copying /etc/hosts to $HOSTS"
-	cp /etc/hosts $HOSTS || fail "can't cp /etc/hosts to $HOSTS" 3
+	cp /etc/hosts $HOSTS || error "can't cp /etc/hosts to $HOSTS" 3
 	log "comparing /etc/hosts and $HOSTS"
-	diff -u /etc/hosts $HOSTS || fail "$HOSTS different" 4
+	diff -u /etc/hosts $HOSTS || error "$HOSTS different" 4
 	log "renaming $HOSTS to $HOSTS.ren"
-	mv $HOSTS $HOSTS.ren || fail "can't rename $HOSTS to $HOSTS.ren" 5
+	mv $HOSTS $HOSTS.ren || error "can't rename $HOSTS to $HOSTS.ren" 5
 	log "copying /etc/hosts to $HOSTS again"
-	cp /etc/hosts $HOSTS || fail "can't cp /etc/hosts to $HOSTS again" 6
+	cp /etc/hosts $HOSTS || error "can't cp /etc/hosts to $HOSTS again" 6
 	log "truncating $HOSTS"
-	> $HOSTS || fail "can't truncate $HOSTS" 8
+	> $HOSTS || error "can't truncate $HOSTS" 8
 	log "removing $HOSTS"
-	rm $HOSTS || fail "can't remove $HOSTS" 9
-	cp /etc/hosts $HOSTS.2 || fail "can't cp /etc/hosts to $HOSTS.2" 7
+	rm $HOSTS || error "can't remove $HOSTS" 9
+	cp /etc/hosts $HOSTS.2 || error "can't cp /etc/hosts to $HOSTS.2" 7
 	log "truncating $HOSTS.2 to $TRUNCSIZE bytes"
 	truncate $HOSTS.2 $TRUNCSIZE
 fi
@@ -87,15 +81,15 @@ fi
 DST=$MOUNT/runtest.$$
 # let's start slowly here...
 log "creating $DST"
-mkdir $DST || fail "can't mkdir $DST" 10
+mkdir $DST || error "can't mkdir $DST" 10
 
 # ok, that hopefully worked, so let's do a little more, with files that
 # haven't changed in the last day (hopefully they don't change during test)
 FILES=`find $RUNTESTS_SRC -type f -mtime +1 | head -n $COUNT`
-[ -z "$FILES" ] && fail "No unchanged files - is $RUNTESTS_SRC a new dir?"
+[ -z "$FILES" ] && error "No unchanged files - is $RUNTESTS_SRC a new dir?"
 
 log "copying files from $RUNTESTS_SRC to $DST$RUNTESTS_SRC at `date`"
-tar cf - $FILES | tar xvf - -C $DST > /dev/null || fail "copying $RUNTESTS_SRC" 11
+tar cf - $FILES | tar xvf - -C $DST > /dev/null || error "copying $RUNTESTS_SRC" 11
 
 log "comparing newly copied files at `date`"
 for f in $FILES; do
@@ -103,7 +97,7 @@ for f in $FILES; do
 	diff -q $f $DST/$f || ERROR=11
 done
 
-[ "$ERROR" ] && fail "old and new files are different" $ERROR
+[ "$ERROR" ] && error "old and new files are different" $ERROR
 log "finished at `date` ($(($(date +%s) - START)))"
 
 $CLEANUP || exit 19
@@ -115,32 +109,32 @@ for f in $FILES; do
 	diff -q $f $DST/$f || ERROR=22
 done
 
-[ "$ERROR" ] && fail "old and new files are different on second diff" $ERROR
+[ "$ERROR" ] && error "old and new files are different on second diff" $ERROR
 
 $CLEANUP || exit 19
 $SETUP || exit 20
 
 log "removing $DST"
-rm -r $V $DST || fail "can't remove $DST" 37
+rm -r $V $DST || error "can't remove $DST" 37
 
 if [ $COUNT -gt 10 -o $COUNT -eq 0 ]; then
 	log "renaming $HOSTS.ren to $HOSTS"
-	mv $HOSTS.ren $HOSTS || fail "can't rename $HOSTS.ren to $HOSTS" 32
+	mv $HOSTS.ren $HOSTS || error "can't rename $HOSTS.ren to $HOSTS" 32
 	log "truncating $HOSTS"
-	> $HOSTS || fail "can't truncate $HOSTS" 34
+	> $HOSTS || error "can't truncate $HOSTS" 34
 	log "removing $HOSTS"
-	rm $HOSTS || fail "can't remove $HOSTS again" 36
+	rm $HOSTS || error "can't remove $HOSTS again" 36
 	log "verifying $HOSTS.2 is $TRUNCSIZE bytes"
 	checkstat -s $TRUNCSIZE $HOSTS.2 || \
-		fail "$HOSTS.2 isn't $TRUNCSIZE bytes" 37
-	rm $HOSTS.2 || fail "can't remove $HOSTS.2" 38
+		error "$HOSTS.2 isn't $TRUNCSIZE bytes" 37
+	rm $HOSTS.2 || error "can't remove $HOSTS.2" 38
 fi
 
 # mkdirmany test (bug 589)
 log "running $MKDIRMANY $MOUNT/base$$ 100"
-$MKDIRMANY $MOUNT/base$$ 100 || fail "mkdirmany failed"
+$MKDIRMANY $MOUNT/base$$ 100 || error "mkdirmany failed"
 log "removing mkdirmany directories"
-rmdir $MOUNT/base$$* || fail "mkdirmany cleanup failed"
+rmdir $MOUNT/base$$* || error "mkdirmany cleanup failed"
 
 log "done"
 
