Remainder of statfs fixup - extN MDS will return minimum of (blocks, inodes) because of EA issues (until that is fixed).
64-bit object number fixups.

Remove ost_get_info (unused, misleading).

diff --git a/lustre/tests/runtests b/lustre/tests/runtests
--- a/lustre/tests/runtests
+++ b/lustre/tests/runtests
@@ -20,13 +20,13 @@ setup_opts $@
 echo "touching $OSCMT"
 touch $OSCMT || fail "can't touch $OSCMT" 2
 echo "copying /etc/hosts to $OSCMT/hosts"
-cp /etc/hosts $OSCMT || fail "can't cp /etc/hosts" 3
+cp /etc/hosts $OSCMT || fail "can't cp /etc/hosts to $OSCMT/hosts" 3
 echo "comparing /etc/hosts and $OSCMT/hosts"
-diff -u /etc/hosts $OSCMT/hosts || fail "/etc/hosts copy different" 4
+diff -u /etc/hosts $OSCMT/hosts || fail "$OSCMT/hosts different" 4
 
 # ok, that hopefully worked, so let's do a little more
 FILES=`find /etc -type f`
-echo "copying files from /etc to $OSCMT"
+echo "copying files from /etc to $OSCMT/etc"
 tar cf - $FILES | tar xvf - -C $OSCMT || fail "copying /etc" 10
 
 echo "comparing newly copied files"
@@ -40,7 +40,7 @@ sh llcleanup.sh $@
 
 echo | sh llrsetup.sh $@ || exit 20
 echo "comparing previously copied files"
-diff -u /etc/hosts $OSCMT/hosts || fail "/etc/hosts is now different" 21
+diff -u /etc/hosts $OSCMT/hosts || fail "$OSTMT/hosts is now different" 21
 
 for f in $FILES; do
 	diff -q $f $OSCMT/$f || ERROR=22
@@ -52,10 +52,11 @@ sh llcleanup.sh $@
 echo | sh llrsetup.sh $@ || exit 24
 
 echo "truncating $OSCMT/hosts"
-> $OSCMT/hosts || fail "can't truncate /etc/hosts" 4
+> $OSCMT/hosts || fail "can't truncate $OSTMT/hosts" 25
 echo "removing $OSCMT/hosts"
-rm $OSCMT/hosts || fail "can't remove $OSCMT/hosts" 25
+rm $OSCMT/hosts || fail "can't remove $OSCMT/hosts" 26
 
-rm -r $OSCMT/etc || fail "can't remove $OSCMT/etc" 26
+echo "removing $OSCMT/etc"
+rm -r $OSCMT/etc || fail "can't remove $OSCMT/etc" 27
 
 sh llcleanup.sh $@
