b=21452 kABI tracking
Changes required to build packages that properly interact with
the kABI tracking included in SLES and RHEL kernels:
- take local copies of the find_requires generators and make modif-
  ications to them so that they can find the kernel artifacts installed
  in our build tree
  + thusly, override the __find_requires macro in all of the RPM
    build operations

Fix package versioning of patchless packages to also include the
timestamp, just like patched packages do, for non-release builds.
Also, remove the _lustre from the kernel version in the lustre
package names for patchless packages.

Note that changes needed to enable the external dependency checker
and thus include kABI dependencies in the RPM are not included here
for RHEL5.  Once RH have updated their kABI whitelist to include the
symbols we need, the patches in bz attachments 30546-7 need to land
for RHEL5 weak modules to work and a bug needs to be filed with OFA
to land the change in bz attachment 30547.

i=wangyb
i=mjmac

diff --git a/build/lbuild-sles10 b/build/lbuild-sles10
--- a/build/lbuild-sles10
+++ b/build/lbuild-sles10
@@ -53,8 +53,17 @@ unpack_linux_devel_rpm-sles10() {
     # get the Module.symvers out of the kenrel-flavor RPM
     local kernelrpm=${callers_rpm/-source-/-$RPMSMPTYPE-}
 
-    if ! rpm2cpio < "$kernelrpm" | cpio -id ./usr/src/linux-${lnxmaj}${lnxmin}-${lnxrel}-obj/$TARGET_ARCH/$RPMSMPTYPE/Module.symvers > /dev/null 2>&1; then
+    if ! rpm2cpio < "$kernelrpm" | cpio -id ./usr/src/linux-${lnxmaj}${lnxmin}-${lnxrel}-obj/$TARGET_ARCH/$RPMSMPTYPE/Module.symvers ./boot/sym\* > /dev/null 2>&1; then
         return 255
+    fi
+
+    # now just sanity check that everything needed to build properly versioned
+    # modules is in place
+    if [ ! -f usr/src/linux-${lnxmaj}${lnxmin}-${lnxrel}-obj/$TARGET_ARCH/$RPMSMPTYPE/Module.symvers ]; then
+        fatal 1 "cannot build kernel modules: the Kernel's Module.symvers is missing."
+    fi
+    if [ ! -f boot/symsets-${lnxmaj}${lnxmin}-${lnxrel}-$RPMSMPTYPE.tar.gz ]; then
+        fatal 1 "cannot build modules: the Kernel's symsets is missing."
     fi
 
     return 0
