Branch b_release_1_8_1 b=20539
Change lbuild-oel5 same as rhel5.

diff --git a/build/lbuild-oel5 b/build/lbuild-oel5
--- a/build/lbuild-oel5
+++ b/build/lbuild-oel5
@@ -3,7 +3,6 @@
 # increment this if you have made a change that should force a new kernel
 # to build built
 #BUILD_GEN=1
-#BUILD_GEN=2	# bz19952: remove -lustre tag from kernel RPM names
 BUILD_GEN=3	# bz19975 enable the building of src.rpms by default
 
 DEVEL_KERNEL_TYPE="devel"
@@ -39,6 +38,7 @@ EOF
     # edit the SPEC with our changes
     sed -i -e 's/^\(%define signmodules \).*/\10/' \
            -e "s/^#% \(define buildid\).*/%\1 ${buildid}/" \
+           -e 's/^\(Name:.*kernel\)/\1-lustre/' \
            -e '/-e $RPM_SOURCE_DIR\/kabi_whitelist_/i\
     rm -f $RPM_SOURCE_DIR/kabi_whitelist_%{_target_cpu}$Flavour' \
            -e '/_sourcedir\/kabitool -b \./a\
@@ -52,35 +52,23 @@ Patch99995: linux-%{kversion}-lustre.patch' \
 ' \
            -e '/^%prep$/,/^# END OF PATCH APPLICATIONS$/s/kernel-%{kversion}/%{name}-%{kversion}/g' \
            -e '/find $RPM_BUILD_ROOT\/lib\/modules\/$KernelVer/a\
-    cp -a fs/ext3/* $RPM_BUILD_ROOT/lib/modules/$KernelVer/build/fs/ext3 \
-    cp -a fs/ext4/* $RPM_BUILD_ROOT/lib/modules/$KernelVer/build/fs/ext4' \
-          SPECS/kernel-2.6.spec
-
-    if $KERNEL_LUSTRE_NAMING; then
-        # these are all of the changes needed because we change the package names
-        # to kernel-lustre-*.  these should all go away when we stop this insanity
-        sed -i -e 's/^\(Name:.*kernel\)/\1-lustre/' \
-               -e '/^Provides: glibc-kernheaders = /a\
+    cp -a fs/ext3/* $RPM_BUILD_ROOT/lib/modules/$KernelVer/build/fs/ext3' \
+           -e '/^Provides: glibc-kernheaders = /a\
 Provides: kernel-headers = %{rpmversion}-%{release}
-Obsoletes: kernel-headers
 ' \
-               -e '/^Provides: kernel-%{_target_cpu} = %{rpmversion}-%{release}$/a\
+           -e '/^Provides: kernel-%{_target_cpu} = %{rpmversion}-%{release}$/a\
 Provides: kernel = %{rpmversion}-%{release}
 ' \
-               -e '/^Provides: kernel-devel-%{_target_cpu} = %{rpmversion}-%{release}$/a\
+           -e '/^Provides: kernel-devel-%{_target_cpu} = %{rpmversion}-%{release}$/a\
 Provides: kernel-devel = %{rpmversion}-%{release}
-Obsoletes: kernel-devel
 ' \
-               -e '/^Provides: %{name}-debuginfo-common-%{_target_cpu} = %{KVERREL}$/a\
+           -e '/^Provides: %{name}-debuginfo-common-%{_target_cpu} = %{KVERREL}$/a\
 Provides: kernel-debuginfo-common = %{KVERREL}
-Obsoletes: kernel-debuginfo-common
 ' \
-               -e '/^Provides: %{name}-debuginfo-%{_target_cpu} = %{KVERREL}$/a\
+           -e '/^Provides: %{name}-debuginfo-%{_target_cpu} = %{KVERREL}$/a\
 Provides: kernel-debuginfo = %{KVERREL}
-Obsoletes: kernel-debuginfo
 ' \
-              SPECS/kernel-2.6.spec
-    fi
+          SPECS/kernel-2.6.spec
 
     # XXX - a building-on-Ubuntu hack
     if grep -q "Ubuntu" /etc/issue; then
@@ -89,10 +77,13 @@ Obsoletes: kernel-debuginfo
           SPECS/kernel-2.6.spec
     fi
 
-    # finally, work around RH bug 491775
-    # XXX - i wonder if we will need to do this enough to formalize a
-    #       patching system.  let's assume not for the time being.
-    patch -s -p0 <<"EOF"
+    # finally, work around RH bug 491775, if needed
+    if ! grep -q "cp -a asm-x86_64 \$RPM_BUILD_ROOT/lib/modules/\$KernelVer/build/include" \
+              SPECS/kernel-2.6.spec; then
+        # XXX - i wonder if we will need to do this ad-hoc patching enough to
+        #       formalize a patching system.  let's assume not for the time
+        #       being.
+        patch -s -p0 <<"EOF" || fatal 1 "Error while patching SPECS/kernel-2.6.spec"
 --- SPECS/kernel-2.6.spec.dist	2009-03-23 20:30:55.000000000 -0400
 +++ SPECS/kernel-2.6.spec	2009-03-23 20:37:03.000000000 -0400
 @@ -6961,6 +6961,10 @@
@@ -107,6 +98,7 @@ Obsoletes: kernel-debuginfo
        cp -a asm-i386 $RPM_BUILD_ROOT/lib/modules/$KernelVer/build/include
      fi
 EOF
+    fi
 
     popd >/dev/null
 
@@ -180,9 +172,5 @@ rpm_BUILD_kernel_dirname() {
     local lnxmin="$3"
     local arch="$4"
 
-    local lustre=""
-    if $KERNEL_LUSTRE_NAMING; then
-        $lustre="-lustre"
-    fi
-    echo kernel${lustre}${lnxmaj}${lnxmin}/linux-${lnxmaj}.$arch
+    echo kernel-lustre${lnxmaj}${lnxmin}/linux-${lnxmaj}.$arch
 }
